namespace TestAPI.Controllers

open Microsoft.AspNetCore.Mvc
open Microsoft.Extensions.Logging
open System

[<ApiController>]
[<Route("api/[controller]")>]
type ValuesController(logger: ILogger<ValuesController>) =
    inherit ControllerBase()
    
    [<HttpGet>]
    member this.Get() =
        logger.LogInformation("GET /api/values called")
        [| 
            {| id = 1; value = "Hello from TestAPI!" |}
            {| id = 2; value = "Generated by TARS" |}
            {| id = 3; value = "F# Web API" |}
        |]
    
    [<HttpGet("{id}")>]
    member this.Get(id: int) =
        logger.LogInformation("GET /api/values/{Id} called", id)
        {| id = id; value = $"Value {id} from TestAPI" |}
    
    [<HttpPost>]
    member this.Post([<FromBody>] value: string) =
        logger.LogInformation("POST /api/values called with: {Value}", value)
        this.Ok({| message = $"Created: {value}"; timestamp = DateTime.UtcNow |})
