open System

type Item = { Name: string; Quantity: int }

let inventory = [
    { Name = "Widget A"; Quantity = 100 }
    { Name = "Widget B"; Quantity = 50 }
]

[<EntryPoint>]
let main argv =
    printfn "🚀 Smart Inventory System (Generated by TARS)"
    printfn "============================================="
    
    printfn "📊 Current Inventory:"
    inventory |> List.iter (fun item ->
        printfn "  %s: %d units" item.Name item.Quantity)
    
    printfn ""
    printfn "✅ TARS successfully generated working inventory code!"
    0
