namespace Tars.Core

open System
open Tars.Core.TemporalKnowledgeGraph

module PatternRecognition =

    /// Detect patterns and anomalies in the graph
    type PatternDetector(graph: TemporalGraph) =
        
        /// Analyze a node and return applicable tags
        member this.TagEntity(entity: TarsEntity) : TaggingResult =
            let neighbors = graph.GetNeighbors(entity)
            let degree = neighbors.Length
            
            let tags = 
                [
                    // Structural: High degree nodes are hubs
                    if degree >= 5 then Some (StructuralTag(level=degree)) else None
                    
                    // Behavioral: Check for frequent updates (mock logic for now)
                    // In real impl, we'd check history of the node
                    
                    // Community: If we had community info, we'd tag it here
                ]
                |> List.choose id
                
            { Entity = entity
              Tags = tags
              AutoGenerated = true
              Confidence = 1.0
              Timestamp = DateTime.UtcNow }

        /// Scan for anomalies in the graph
        member this.DetectAnomalies() : AnomalyEntity list =
            let nodes = graph.GetNodes()
            let edges = graph.GetEdges()
            
            let anomalies = 
                nodes 
                |> List.collect (fun node ->
                    let neighbors = graph.GetNeighbors(node)
                    
                    // Anomaly 1: Isolated nodes (no edges)
                    // Only consider concepts or code modules, not anomalies themselves
                    match node with
                    | AnomalyE _ -> []
                    | _ ->
                        if List.isEmpty neighbors then
                            [{ Type = AnomalyType.PerformanceIssue "Isolated node detected"
                               Location = TarsEntity.getId node
                               Severity = AnomalySeverity.Low
                               DetectedAt = DateTime.UtcNow
                               ResolvedAt = None }]
                        else
                            []
                )
                
            // Anomaly 2: Contradictions (Explicit Contradicts edges)
            let contradictions =
                edges
                |> List.choose (fun edge ->
                    match edge.Fact with
                    | Contradicts(source, target, _) ->
                        Some { Type = AnomalyType.Inconsistency $"Explicit contradiction between {TarsEntity.getId source} and {TarsEntity.getId target}"
                               Location = TarsEntity.getId source
                               Severity = AnomalySeverity.High
                               DetectedAt = DateTime.UtcNow
                               ResolvedAt = None }
                    | _ -> None
                )
                
            anomalies @ contradictions
