apiVersion: v1
kind: Service
metadata:
  name: tars-engine-service
  namespace: tars-system
  labels:
    app: tars-engine
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: tars-engine
---
apiVersion: v1
kind: Service
metadata:
  name: tars-engine-service-headless
  namespace: tars-system
  labels:
    app: tars-engine
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: tars-engine