namespace TarsEngine.FSharp.Core.Closures

open System
open System.Collections.Generic
open System.Globalization
open System.Text.Json
open Microsoft.Extensions.Logging

/// Game theory agent types supported by the evolutionary closure pipeline.
type GameTheoryAgentType =
    | QuantalResponseEquilibrium of float
    | CognitiveHierarchy of int
    | NoRegretLearning of float
    | EvolutionaryGameTheory of float
    | CorrelatedEquilibrium of float
    | MachineLearningAgent of string

/// Coordination strategies recognised by the closure pipeline.
type CoordinationStrategy =
    | Hierarchical of leaderId: string
    | Democratic
    | Specialized
    | Swarm
    | FractalSelfOrganizing

/// Unified evolutionary closure factory with deterministic, testable behaviour.
module UnifiedEvolutionaryClosureFactory =


    /// Representation of a grammar supplied to the evolution closure.
    type GrammarDefinition =
        { Name: string
          Rules: string list
          UsageCount: int option }

    /// Representation of an agent profile supplied to the coordination closure.
    type AgentProfile =
        { Name: string
          Role: string
          Skill: float
          Availability: float }

    /// Summary produced by the grammar evolution closure.
    type GrammarEvolutionSummary =
        { TeamName: string
          EvolutionGoal: string
          RankedGrammars: (string * float) list
          AverageRuleLength: float
          Recommendations: string list }

    /// Summary produced by the multi-agent coordination closure.
    type CoordinationSummary =
        { Strategy: CoordinationStrategy
          TeamScore: float
          RoleCoverage: Map<string, int>
          Bottlenecks: string list
          SuggestedPairings: (string * string) list }

    /// Artifact generated by the fractal metascript closure.
    type FractalMetascriptArtifact =
        { Pattern: string
          Depth: int
          Script: string
          NodeCount: int
          BranchingFactor: float }

    /// Summary produced by dynamic metascript closures constructed from external grammars.
    type DynamicMetascriptSummary =
        { Name: string
          SourcePath: string option
          RuleCount: int
          MaxDepth: int
          SpawnedAgents: (GameTheoryAgentType * int * CoordinationStrategy) list
          Connections: (string * string * string) list
          Metrics: Map<string, float>
          RepeatedPatterns: (string * int) list }

    /// Intermediate representation for dynamic metascript closures generated from grammars.
    type DynamicMetascriptRule =
        | SpawnAgentRule of GameTheoryAgentType * int * CoordinationStrategy
        | ConnectAgentsRule of string * string * string
        | EmitMetricRule of string * float
        | RepeatPatternRule of string * int

    type DynamicMetascriptSpec =
        { Name: string
          Rules: DynamicMetascriptRule list
          MaxDepth: int
          SourcePath: string option
          Expectations: Map<string, string> option }

    /// Supported closure types.
    type EvolutionaryClosureType =
        | GrammarEvolutionClosure of teamName: string * evolutionGoal: string
        | MultiAgentCoordinationClosure of coordinationStrategy: CoordinationStrategy
        | FractalMetascriptGeneratorClosure of depth: int * pattern: string
        | DynamicMetascriptClosure of spec: DynamicMetascriptSpec

    /// Execution context for a closure instance.
    type EvolutionaryClosureContext =
        { ClosureId: string
          Name: string
          CreatedAt: DateTime
          Parameters: Map<string, obj>
          Environment: Map<string, obj> }

    /// Execution result produced by a closure.
    type EvolutionaryClosureResult =
        { Success: bool
          Output: obj option
          Error: string option
          ExecutionTime: TimeSpan
          EvolutionData: Map<string, obj>
          GeneratedArtifacts: string list
          PerformanceImpact: Map<string, float>
          NextEvolutionSteps: string list }

    /// Unified closure factory implementation.
    type UnifiedEvolutionaryClosureFactory(logger: ILogger<UnifiedEvolutionaryClosureFactory>) =

        let jsonOptions =
            JsonSerializerOptions(PropertyNameCaseInsensitive = true)

        let tryGetString key (source: Map<string, obj>) =
            source
            |> Map.tryFind key
            |> Option.bind (fun value ->
                match value with
                | :? string as str when not (String.IsNullOrWhiteSpace(str)) -> Some str
                | :? JsonElement as json when json.ValueKind = JsonValueKind.String ->
                    let str = json.GetString()
                    if String.IsNullOrWhiteSpace(str) then None else Some str
                | _ -> None)

        let toObjectMap (values: (string * obj) list) =
            values |> List.fold (fun acc (k, v) -> Map.add k v acc) Map.empty

        let clamp01 (value: float) =
            if value < 0.0 then 0.0
            elif value > 1.0 then 1.0
            else value

        let avg (values: float list) =
            if values.IsEmpty then 0.0 else values |> List.average

        let normaliseScores (scores: (string * float) list) =
            match scores with
            | [] -> []
            | _ ->
                let maxScore = scores |> List.maxBy snd |> snd
                if maxScore <= 0.0 then scores
                else scores |> List.map (fun (name, score) -> name, score / maxScore)

        let summariseRecommendations (goal: string) (grammars: GrammarDefinition list) =
            let lowCoverage =
                grammars
                |> List.filter (fun g -> g.Rules.Length < 5)
                |> List.map (fun g -> $"Increase rule coverage for '{g.Name}'.")

            let goalSpecific =
                if goal.ToLowerInvariant().Contains("optimiz") then
                    [ "Review transition costs for frequently used rules."
                      "Introduce heuristic evaluation for high-complexity grammars." ]
                elif goal.ToLowerInvariant().Contains("safety") then
                    [ "Ensure each grammar includes explicit failure states."
                      "Add validation rules to guard against invalid transitions." ]
                else
                    [ "Capture evaluation metrics for the highest scoring grammar."
                      "Publish evolution summary to the team knowledge base." ]

            (lowCoverage @ goalSpecific)
            |> List.distinct

        let evaluateGrammars (grammars: GrammarDefinition list) =
            let ranked =
                grammars
                |> List.map (fun g ->
                    let ruleLengthScore =
                        g.Rules
                        |> List.map (fun r -> float r.Length)
                        |> avg

                    let usageScore =
                        g.UsageCount
                        |> Option.map float
                        |> Option.defaultValue 0.0

                    let score =
                        float g.Rules.Length
                        + (ruleLengthScore / 100.0)
                        + (usageScore / 10.0)

                    g.Name, score)
                |> List.sortByDescending snd

            let averageRuleLength =
                grammars
                |> List.collect (fun g -> g.Rules)
                |> List.map (fun r -> float r.Length)
                |> avg

            ranked, averageRuleLength

        let evaluateCoordination (strategy: CoordinationStrategy) (agents: AgentProfile list) =
            let roleCoverage =
                agents
                |> List.countBy (fun agent -> agent.Role)
                |> Map.ofList

            let skillAverage = agents |> List.map (fun a -> a.Skill) |> avg
            let availabilityAverage = agents |> List.map (fun a -> a.Availability) |> avg
            let teamScore = clamp01 ((skillAverage + availabilityAverage) / 2.0)

            let bottlenecks =
                roleCoverage
                |> Map.toList
                |> List.filter (fun (_, count) -> count = 1)
                |> List.map (fun (role, _) -> $"Only one agent covers role '{role}'.")

            let sortedAgents =
                agents
                |> List.sortByDescending (fun agent -> agent.Skill * agent.Availability)

            let pairings =
                sortedAgents
                |> Seq.pairwise
                |> Seq.map (fun (a, b) -> a.Name, b.Name)
                |> Seq.toList

            { Strategy = strategy
              TeamScore = teamScore
              RoleCoverage = roleCoverage
              Bottlenecks = bottlenecks
              SuggestedPairings = pairings }

        let buildFractalScript pattern depth =
            let rec build level prefix =
                if level > depth then []
                else
                    let currentNode = $"{prefix}{pattern}-{level}"
                    let children =
                        [ $"{currentNode}-A"
                          $"{currentNode}-B" ]

                    let line = $"NODE {currentNode} CHILDREN {String.Join(',', children)}"
                    line :: (children |> List.collect (fun child -> build (level + 1) (child + "/")))

            build 1 ""

        let generateFractalArtifact pattern depth =
            let scriptLines = buildFractalScript pattern depth
            let nodeCount = scriptLines.Length
            let branchingFactor =
                if depth <= 1 then 0.0
                else float nodeCount / float depth

            { Pattern = pattern
              Depth = depth
              Script = String.Join(Environment.NewLine, scriptLines)
              NodeCount = nodeCount
              BranchingFactor = branchingFactor }

        let summariseDynamicMetascript (spec: DynamicMetascriptSpec) =
            let updateRepeat repeats name depth =
                let current = repeats |> Map.tryFind name |> Option.defaultValue 0
                repeats |> Map.add name (current + depth)

            let finalSpawn, finalConnections, finalMetrics, finalRepeats =
                spec.Rules
                |> List.fold
                    (fun (spawn, connections, metrics, repeats) rule ->
                        match rule with
                        | SpawnAgentRule(agentType, count, strategy) ->
                            ((agentType, count, strategy) :: spawn, connections, metrics, repeats)
                        | ConnectAgentsRule(source, target, label) ->
                            (spawn, (source, target, label) :: connections, metrics, repeats)
                        | EmitMetricRule(metric, value) ->
                            let updatedMetrics = metrics |> Map.add metric value
                            (spawn, connections, updatedMetrics, repeats)
                        | RepeatPatternRule(name, depth) ->
                            let updatedRepeats = updateRepeat repeats name depth
                            (spawn, connections, metrics, updatedRepeats))
                    ([], [], Map.empty, Map.empty)

            { Name = spec.Name
              SourcePath = spec.SourcePath
              RuleCount = spec.Rules.Length
              MaxDepth = spec.MaxDepth
              SpawnedAgents = List.rev finalSpawn
              Connections = List.rev finalConnections
              Metrics = finalMetrics
              RepeatedPatterns = finalRepeats |> Map.toList }

        let toGrammarDefinitions (payload: string) : GrammarDefinition list option =
            try
                use document = JsonDocument.Parse(payload)
                let grammars =
                    document.RootElement.EnumerateArray()
                    |> Seq.choose (fun element ->
                        if element.ValueKind <> JsonValueKind.Object then
                            None
                        else
                            let tryString (name: string) =
                                let mutable property = Unchecked.defaultof<JsonElement>
                                if element.TryGetProperty(name, &property) && property.ValueKind = JsonValueKind.String then
                                    property.GetString() |> Option.ofObj
                                else
                                    None
                            let tryStringArray (name: string) =
                                let mutable property = Unchecked.defaultof<JsonElement>
                                if element.TryGetProperty(name, &property) && property.ValueKind = JsonValueKind.Array then
                                    property.EnumerateArray()
                                    |> Seq.choose (fun item ->
                                        if item.ValueKind = JsonValueKind.String then
                                            item.GetString() |> Option.ofObj
                                        else
                                            None)
                                    |> Seq.toList
                                    |> Some
                                else
                                    None

                            let usageCount =
                                let mutable property = Unchecked.defaultof<JsonElement>
                                if element.TryGetProperty("usage", &property) && property.ValueKind = JsonValueKind.Number then
                                    let mutable value = 0
                                    if property.TryGetInt32(&value) then Some value else None
                                else
                                    None

                            match tryString "name", tryStringArray "rules" with
                            | Some name, Some rules when not (String.IsNullOrWhiteSpace(name)) && not rules.IsEmpty ->
                                Some { Name = name; Rules = rules; UsageCount = usageCount }
                            | _ -> None)
                    |> Seq.toList

                Some grammars
            with
            | :? JsonException as ex ->
                logger.LogWarning(ex, "Failed to decode grammar payload: {Payload}", payload)
                None

        let toAgentProfiles (payload: string) : AgentProfile list option =
            try
                use document = JsonDocument.Parse(payload)
                let agents =
                    document.RootElement.EnumerateArray()
                    |> Seq.choose (fun element ->
                        if element.ValueKind <> JsonValueKind.Object then
                            None
                        else
                            let tryString (name: string) =
                                let mutable property = Unchecked.defaultof<JsonElement>
                                if element.TryGetProperty(name, &property) && property.ValueKind = JsonValueKind.String then
                                    property.GetString() |> Option.ofObj
                                else
                                    None
                            let tryFloat (name: string) =
                                let mutable property = Unchecked.defaultof<JsonElement>
                                if element.TryGetProperty(name, &property) && property.ValueKind = JsonValueKind.Number then
                                    let mutable value = 0.0
                                    if property.TryGetDouble(&value) then Some (clamp01 value) else None
                                else
                                    None

                            match tryString "name", tryString "role", tryFloat "skill", tryFloat "availability" with
                            | Some name, Some role, Some skill, Some availability ->
                                Some { Name = name; Role = role; Skill = skill; Availability = availability }
                            | _ -> None)
                    |> Seq.toList

                Some agents
            with
            | :? JsonException as ex ->
                logger.LogWarning(ex, "Failed to decode agent payload: {Payload}", payload)
                None

        let registerExecution
            (context: EvolutionaryClosureContext)
            (resultBuilder: unit -> EvolutionaryClosureResult)
            =
            async {
                let startTime = DateTime.UtcNow
                let result = resultBuilder()
                let executionTime = DateTime.UtcNow - startTime
                return { result with ExecutionTime = executionTime }
            }

        member this.CreateClosure(closureType: EvolutionaryClosureType, name: string, environment: Map<string, obj>) =
            let closureId = Guid.NewGuid().ToString("N")[..7]
            let baseContext =
                { ClosureId = closureId
                  Name = name
                  CreatedAt = DateTime.UtcNow
                  Parameters = Map.empty
                  Environment = environment }

            match closureType with
            | GrammarEvolutionClosure(teamName, evolutionGoal) ->
                fun parameters ->
                    registerExecution { baseContext with Parameters = parameters } (fun () ->
                        let grammarPayload =
                            match tryGetString "grammars" parameters with
                            | Some payload -> Some payload
                            | None -> tryGetString "grammars" environment

                        match grammarPayload |> Option.bind toGrammarDefinitions with
                        | None ->
                            { Success = false
                              Output = None
                              Error = Some "Grammar definitions are required for evolution analysis."
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData = Map.empty
                              GeneratedArtifacts = []
                              PerformanceImpact = Map.empty
                              NextEvolutionSteps = [] }
                        | Some grammars when grammars.IsEmpty ->
                            { Success = false
                              Output = None
                              Error = Some "At least one grammar definition must be provided."
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData = Map.empty
                              GeneratedArtifacts = []
                              PerformanceImpact = Map.empty
                              NextEvolutionSteps = [] }
                        | Some grammars ->
                            let ranked, averageRuleLength = evaluateGrammars grammars
                            let recommendations = summariseRecommendations evolutionGoal grammars
                            let summary =
                                { TeamName = teamName
                                  EvolutionGoal = evolutionGoal
                                  RankedGrammars = ranked
                                  AverageRuleLength = averageRuleLength
                                  Recommendations = recommendations }

                            let artifactText =
                                let rankedText =
                                    ranked
                                    |> List.map (fun (name, score) ->
                                        let formatted = score.ToString("F2", CultureInfo.InvariantCulture)
                                        $"{name}:{formatted}")
                                    |> fun entries -> String.Join(", ", entries)

                                $"team=%s{teamName} goal=\"%s{evolutionGoal}\" ranked=[%s{rankedText}]"

                            { Success = true
                              Output = Some (box summary)
                              Error = None
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData =
                                  [ "team_name", box teamName
                                    "goal", box evolutionGoal
                                    "grammar_count", box (float grammars.Length)
                                    "average_rule_length", box averageRuleLength ]
                                  |> toObjectMap
                              GeneratedArtifacts = [ artifactText ]
                              PerformanceImpact =
                                  ranked
                                  |> normaliseScores
                                  |> List.truncate 3
                                  |> List.map (fun (name, score) -> name, clamp01 score)
                                  |> Map.ofList
                              NextEvolutionSteps = recommendations }
                    )

            | MultiAgentCoordinationClosure strategy ->
                fun parameters ->
                    registerExecution { baseContext with Parameters = parameters } (fun () ->
                        let agentPayload =
                            match tryGetString "agents" parameters with
                            | Some payload -> Some payload
                            | None -> tryGetString "agents" environment

                        match agentPayload |> Option.bind toAgentProfiles with
                        | None ->
                            { Success = false
                              Output = None
                              Error = Some "Agent profiles are required for coordination analysis."
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData = Map.empty
                              GeneratedArtifacts = []
                              PerformanceImpact = Map.empty
                              NextEvolutionSteps = [] }
                        | Some agents when agents.IsEmpty ->
                            { Success = false
                              Output = None
                              Error = Some "At least one agent profile must be provided."
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData = Map.empty
                              GeneratedArtifacts = []
                              PerformanceImpact = Map.empty
                              NextEvolutionSteps = [] }
                        | Some agents ->
                            let summary = evaluateCoordination strategy agents
                            let performanceImpact =
                                let coverage = clamp01 (float summary.RoleCoverage.Count / float agents.Length)
                                let availability =
                                    agents
                                    |> List.map (fun agent -> agent.Availability)
                                    |> avg
                                [ "team_score", summary.TeamScore
                                  "coverage", coverage
                                  "availability", availability ]
                                |> Map.ofList

                            let coverageText =
                                summary.RoleCoverage
                                |> Map.toList
                                |> List.map (fun (role, count) -> $"{role}:{count}")
                                |> fun entries -> String.Join(", ", entries)

                            let pairingSummary =
                                summary.SuggestedPairings
                                |> Seq.map (fun (a, b) -> $"{a}↔{b}")
                                |> fun pairs -> String.Join(", ", pairs)

                            let artifactText =
                                $"coordination strategy=%A{summary.Strategy} score=%.2f{summary.TeamScore} coverage=[%s{coverageText}]"

                            let nextSteps =
                                (summary.Bottlenecks
                                 @ [ $"Pair high-skill agents: %s{pairingSummary}" ])
                                |> List.distinct

                            { Success = true
                              Output = Some (box summary)
                              Error = None
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData =
                                  [ "agent_count", box agents.Length
                                    "strategy", box (summary.Strategy.ToString())
                                    "role_coverage", box coverageText ]
                                  |> toObjectMap
                              GeneratedArtifacts = [ artifactText ]
                              PerformanceImpact = performanceImpact
                              NextEvolutionSteps = nextSteps }
                    )

            | FractalMetascriptGeneratorClosure(depth, pattern) ->
                fun parameters ->
                    registerExecution { baseContext with Parameters = parameters } (fun () ->
                        if depth <= 0 then
                            { Success = false
                              Output = None
                              Error = Some "Depth must be greater than zero for fractal metascript generation."
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData = Map.empty
                              GeneratedArtifacts = []
                              PerformanceImpact = Map.empty
                              NextEvolutionSteps = [] }
                        else
                            let artifact = generateFractalArtifact pattern depth
                            { Success = true
                              Output = Some (box artifact)
                              Error = None
                              ExecutionTime = TimeSpan.Zero
                              EvolutionData =
                                  [ "pattern", box artifact.Pattern
                                    "depth", box artifact.Depth
                                    "node_count", box artifact.NodeCount
                                    "branching_factor", box artifact.BranchingFactor ]
                                  |> toObjectMap
                              GeneratedArtifacts = [ artifact.Script ]
                              PerformanceImpact =
                                  [ "structural_complexity", clamp01 (float artifact.NodeCount / 64.0)
                                    "branching_factor", clamp01 artifact.BranchingFactor ]
                                  |> Map.ofList
                              NextEvolutionSteps =
                                  [ "Review generated metascript for recursion correctness."
                                    "Integrate metascript into evolution pipeline."
                                    "Assign ownership for validation run." ] }
                    )

            | DynamicMetascriptClosure spec ->
                fun parameters ->
                    registerExecution { baseContext with Parameters = parameters } (fun () ->
                        let summary = summariseDynamicMetascript spec
                        let artifactText =
                            match summary.SourcePath with
                            | Some path -> $"dynamic metascript %s{summary.Name} (rules=%d{summary.RuleCount} source=%s{path})"
                            | None -> $"dynamic metascript %s{summary.Name} (rules=%d{summary.RuleCount} inline)"

                        let evolutionData =
                            [ "dsl.metascript.rule_count", box summary.RuleCount
                              "dsl.metascript.max_depth", box summary.MaxDepth
                              "dsl.metascript.spawn_count", box summary.SpawnedAgents.Length
                              "dsl.metascript.connection_count", box summary.Connections.Length
                              "dsl.metascript.repeated_patterns", box (summary.RepeatedPatterns |> List.map fst) ]
                            |> (fun entries ->
                                match summary.SourcePath with
                                | Some path -> ("dsl.metascript.source", box path) :: entries
                                | None -> entries)
                            |> toObjectMap

                        let performanceImpact =
                            summary.Metrics
                            |> Map.map (fun _ value -> clamp01 value)

                        let nextSteps =
                            [ "Validate dynamic closure grammar against production constraints."
                              "Run rehearsal execution in sandboxed environment."
                              "Publish documentation for newly generated closure behaviour." ]

                        { Success = true
                          Output = Some (box summary)
                          Error = None
                          ExecutionTime = TimeSpan.Zero
                          EvolutionData = evolutionData
                          GeneratedArtifacts = [ artifactText ]
                          PerformanceImpact = performanceImpact
                          NextEvolutionSteps = nextSteps })




