// TARS System Types - Generated by TARS itself

export interface TarsSystemStatus {
  isOnline: boolean;
  version: string;
  uptime: number;
  cpuUsage: number;
  memoryUsage: number;
  cudaAvailable: boolean;
  agentCount: number;
}

export interface TarsProject {
  id: string;
  name: string;
  description: string;
  status: 'creating' | 'active' | 'completed' | 'error';
  createdAt: string;
  lastModified: string;
  files: string[];
  tests: TestResult[];
}

export interface TarsMetascript {
  id: string;
  name: string;
  description: string;
  status: 'idle' | 'running' | 'completed' | 'error';
  executionTime?: number;
  output?: string;
  variables: Record<string, any>;
}

export interface TarsAgent {
  id: string;
  name: string;
  persona: string;
  status: 'idle' | 'active' | 'busy' | 'error';
  capabilities: string[];
  currentTask?: string;
  performance: AgentPerformance;
}

export interface AgentPerformance {
  tasksCompleted: number;
  averageExecutionTime: number;
  successRate: number;
  lastActivity: string;
}

export interface TestResult {
  id: string;
  name: string;
  status: 'passed' | 'failed' | 'running';
  duration: number;
  message?: string;
}

export interface PerformanceMetrics {
  cuda: {
    available: boolean;
    deviceName?: string;
    memoryUsed: number;
    memoryTotal: number;
    searchesPerSecond: number;
  };
  system: {
    cpuUsage: number;
    memoryUsage: number;
    diskUsage: number;
    networkActivity: number;
  };
  agents: {
    totalAgents: number;
    activeAgents: number;
    tasksInQueue: number;
    averageResponseTime: number;
  };
}

export interface CommandResult {
  success: boolean;
  output: string;
  error?: string;
  executionTime: number;
}
