namespace ApiService.Core.Domain

open System

/// User domain model
type User = {
    Id: Guid
    Email: string
    FirstName: string option
    LastName: string option
    CreatedAt: DateTime
    IsActive: bool
}

/// Entity domain model
type Entity = {
    Id: Guid
    Name: string
    Description: string option
    OwnerId: Guid
    Data: Map<string, obj>
    CreatedAt: DateTime
    UpdatedAt: DateTime
}

/// Common result type for operations
type Result<'TSuccess, 'TError> =
    | Success of 'TSuccess
    | Error of 'TError

/// Validation error
type ValidationError = {
    Field: string
    Message: string
}

/// Domain error types
type DomainError =
    | ValidationErrors of ValidationError list
    | NotFound of string
    | Unauthorized of string
    | BusinessRuleViolation of string

// Generated by TARS Senior Development Team
