namespace TarsEngine.FSharp.DynamicUI

open System

/// Agent team that dynamically builds UI components
type AgentTeam = {
    Id: string
    Name: string
    Role: string
    Expertise: string list
    CycleIntervalMs: int
    IsActive: bool
    LastExecution: DateTime option
    ComponentsGenerated: int
    CurrentTask: string option
}

/// Dynamic UI component generated by agents
type DynamicComponent = {
    Id: string
    Type: string
    GeneratedBy: string
    CreatedAt: DateTime
    Properties: Map<string, obj>
    HtmlContent: string option
    ThreeJSObject: obj option
    IsVisible: bool
}

/// TARS agent status for visualization
type TarsAgent = {
    Id: string
    Name: string
    Type: string
    Position: float * float * float
    Status: AgentStatus
    TaskCount: int
    Department: string
}

and AgentStatus =
    | Running
    | Idle
    | Processing
    | Error

/// 3D scene requirements from DSL
type SceneRequirements = {
    AgentTreeVisible: bool
    ShowConnections: bool
    VisualizationStyle: VisualizationStyle
    InteractionMode: InteractionMode
    PerformanceMode: PerformanceMode
    UpdateFrequency: int
}

and VisualizationStyle =
    | Interstellar
    | Cyberpunk
    | Minimal
    | Organic

and InteractionMode =
    | Orbit
    | FlyThrough
    | FirstPerson
    | Cinematic

and PerformanceMode =
    | HighQuality
    | Balanced
    | Performance

/// Real-time metrics
type PerformanceMetrics = {
    FPS: float
    ComponentCount: int
    ActiveAgents: int
    MemoryUsage: float
    RenderTime: float
    WebGPUActive: bool
}

/// UI generation request from requirements analysis
type UIGenerationRequest = {
    RequestId: string
    ComponentType: string
    Requirements: Map<string, obj>
    Priority: int
    RequestedBy: string
    Deadline: DateTime option
}

/// Agent coordination message
type AgentMessage =
    | StartGeneration of UIGenerationRequest
    | ComponentGenerated of DynamicComponent
    | RequirementsChanged of SceneRequirements
    | PerformanceUpdate of PerformanceMetrics
    | AgentStatusUpdate of string * AgentStatus
    | OptimizationNeeded of string
