
open System
open System.Text
open System.Diagnostics
open TarsEngine.FSharp.Cli.Core

/// <summary>
/// EVOLVED Main entry point for the TARS CLI application.
/// Enhanced with better error handling, performance monitoring, and user experience.
/// Generated by TARS Self-Evolution System
/// </summary>
[<EntryPoint>]
let main args =
    try
        // EVOLUTION: Enhanced console setup
        Console.OutputEncoding <- Encoding.UTF8
        Console.InputEncoding <- Encoding.UTF8
        
        // EVOLUTION: Performance monitoring
        let stopwatch = Stopwatch.StartNew()
        let startTime = DateTime.UtcNow
        
        // EVOLUTION: Enhanced startup message
        if args |> Array.contains "--verbose" then
            Console.WriteLine("🚀 TARS CLI (Evolved Version) - Starting...")
            Console.WriteLine($"Started at: {startTime:yyyy-MM-dd HH:mm:ss}")
        
        // EVOLUTION: Improved error handling with context
        let app = CliApplication()
        let exitCode = 
            try
                let result = app.RunAsync(args).Result
                
                // EVOLUTION: Success logging
                if args |> Array.contains "--verbose" then
                    stopwatch.Stop()
                    Console.WriteLine($"✅ Command completed in {stopwatch.ElapsedMilliseconds}ms")
                
                result
            with
            | :? AggregateException as aggEx ->
                let innerEx = aggEx.GetBaseException()
                Console.WriteLine($"❌ TARS Error: {innerEx.Message}")
                if args |> Array.contains "--verbose" || args |> Array.contains "--debug" then
                    Console.WriteLine($"📍 Location: {innerEx.Source}")
                    Console.WriteLine($"🔍 Stack trace: {innerEx.StackTrace}")
                1
            | :? TimeoutException ->
                Console.WriteLine("⏰ TARS Error: Operation timed out")
                Console.WriteLine("💡 Try using --timeout parameter to increase timeout")
                1
            | ex ->
                Console.WriteLine($"❌ TARS Error: {ex.Message}")
                Console.WriteLine("💡 Use 'tars help' for usage information")
                if args |> Array.contains "--debug" then
                    Console.WriteLine($"🔍 Debug info: {ex.StackTrace}")
                1
        
        // EVOLUTION: Performance reporting
        if args |> Array.contains "--timing" then
            stopwatch.Stop()
            Console.WriteLine($"⏱️  Total execution time: {stopwatch.ElapsedMilliseconds}ms")
            Console.WriteLine($"📊 Memory usage: {GC.GetTotalMemory(false) / 1024 / 1024}MB")
        
        exitCode
    with
    | ex ->
        // EVOLUTION: Ultimate fallback with helpful guidance
        Console.WriteLine($"💥 TARS Fatal Error: {ex.Message}")
        Console.WriteLine("🆘 This is an unexpected error. Please report this issue.")
        Console.WriteLine("💡 Use 'tars help' for usage information.")
        Console.WriteLine("🔧 Use 'tars diagnose' to check system health.")
        1
