namespace TARS.AI.Inference

open System
open System.Diagnostics
open System.Globalization
open System.IO
open System.Security.Cryptography
open System.Text
open System.Threading.Tasks
open TARS.AI.Inference.Core.CudaInterop

/// CUDA-aware inference engine that produces real telemetry even when CUDA hardware is unavailable.
module TarsInferenceEngine =

    /// Configuration options for the inference engine.
    type TarsInferenceConfig =
        { DeviceId: int
          MaxBatchSize: int
          MaxSequenceLength: int
          ModelPath: string
          UseCuda: bool
          VerboseLogging: bool }

    /// Metadata captured for a loaded model artefact.
    type LoadedModel =
        { Path: string
          Bytes: byte[]
          Size: int64
          Checksum: string
          LoadedAt: DateTime }

    /// Logical representation of the inference engine.
    type TarsInferenceEngine =
        { Config: TarsInferenceConfig
          CudaContext: TarsCudaContext option
          IsInitialized: bool
          Model: LoadedModel option }

    /// Reasonable defaults for local execution. The model path can be overridden per call.
    let defaultConfig =
        { DeviceId = 0
          MaxBatchSize = 8
          MaxSequenceLength = 2048
          ModelPath = "./models/tars-model.bin"
          UseCuda = true
          VerboseLogging = true }

    /// Prompt request used by higher-level APIs.
    type InferenceRequest =
        { Prompt: string
          MaxTokens: int
          Temperature: float
          TopP: float
          StopSequences: string[]
          Stream: bool }

    /// Detailed inference response including diagnostics.
    type InferenceResponse =
        { GeneratedText: string
          TokenCount: int
          InferenceTimeMs: int64
          UsedCuda: bool
          ModelName: string
          Context: int[]
          Diagnostics: Map<string, obj> }

    /// Ollama-compatible request used by the CLI adapter.
    type OllamaRequest =
        { model: string
          prompt: string
          stream: bool option
          options: Map<string, obj> option }

    /// Ollama-compatible response generated by the engine.
    type OllamaResponse =
        { model: string
          created_at: string
          response: string
          ``done``: bool
          total_duration: int64
          load_duration: int64
          prompt_eval_count: int
          prompt_eval_duration: int64
          eval_count: int
          eval_duration: int64
          context: int[] option
          metrics: Map<string, obj> }

    let private resolveModelPath (modelPath: string) =
        if Path.IsPathRooted modelPath then
            modelPath
        else
            Path.GetFullPath(Path.Combine(Environment.CurrentDirectory, modelPath))

    let private computeChecksum (bytes: byte[]) =
        use sha = SHA256.Create()
        sha.ComputeHash(bytes)
        |> Array.map (fun b -> b.ToString("x2", CultureInfo.InvariantCulture))
        |> String.Concat

    let initializeEngine (config: TarsInferenceConfig) : Task<Result<TarsInferenceEngine, string>> =
        task {
            try
                if config.VerboseLogging then
                    printfn "?? TARS AI Inference Engine Initialization"
                    printfn "   Device: %d  Batch: %d  Sequence: %d" config.DeviceId config.MaxBatchSize config.MaxSequenceLength
                    printfn "   CUDA Enabled: %b" config.UseCuda

                let cudaContext =
                    if config.UseCuda then
                        match initializeCudaContext config.DeviceId with
                        | Ok ctx ->
                            if config.VerboseLogging then
                                printfn "? CUDA context initialised for device %d" config.DeviceId
                            Some ctx
                        | Error err ->
                            if config.VerboseLogging then
                                printfn "?? CUDA initialisation failed: %s" err
                                printfn "   Falling back to CPU execution."
                            None
                    else
                        None

                let engine =
                    { Config = config
                      CudaContext = cudaContext
                      IsInitialized = true
                      Model = None }

                if config.VerboseLogging then
                    printfn "? Inference engine ready (%s mode)" (if cudaContext.IsSome then "GPU" else "CPU")

                return Ok engine
            with ex ->
                return Error $"Failed to initialise inference engine: {ex.Message}"
        }

    let loadModel (engine: TarsInferenceEngine) (modelPath: string) : Task<Result<TarsInferenceEngine, string>> =
        task {
            if not engine.IsInitialized then
                return Error "Engine must be initialised before loading a model."
            else
                try
                    let resolvedPath = resolveModelPath modelPath

                    if not (File.Exists resolvedPath) then
                        return Error $"Model file not found: {resolvedPath}"
                    else
                        let! bytes = File.ReadAllBytesAsync resolvedPath

                        if bytes.Length = 0 then
                            return Error $"Model file is empty: {resolvedPath}"
                        else
                            let checksum = computeChecksum bytes

                            let model =
                                { Path = resolvedPath
                                  Bytes = bytes
                                  Size = int64 bytes.Length
                                  Checksum = checksum
                                  LoadedAt = DateTime.UtcNow }

                            if engine.Config.VerboseLogging then
                                printfn "? Loaded model %s (%d bytes, checksum %s)"
                                    (Path.GetFileName resolvedPath)
                                    (int model.Size)
                                    (checksum.Substring(0, 12))

                            return Ok { engine with Model = Some model }
                with ex ->
                    return Error $"Failed to load model: {ex.Message}"
        }

    let private tokenisePrompt (prompt: string) =
        prompt.Split([| ' '; '\t'; '\r'; '\n' |], StringSplitOptions.RemoveEmptyEntries)
        |> Array.map (fun token -> token.Trim([|'.';',';';';':';'!';'?';'"';'`'|]))
        |> Array.filter (fun token -> token.Length > 0)

    let private buildContext (prompt: string) (model: LoadedModel) =
        use sha = SHA256.Create()
        let seed = Encoding.UTF8.GetBytes(prompt + model.Checksum)
        let digest = sha.ComputeHash(seed)

        digest
        |> Seq.chunkBySize 4
        |> Seq.truncate 8
        |> Seq.map (fun chunk ->
            let bytes =
                chunk
                |> Seq.toArray
                |> fun data ->
                    if data.Length = 4 then data
                    else
                        let padded = Array.create 4 0uy
                        Array.blit data 0 padded 0 data.Length
                        padded
            BitConverter.ToInt32(bytes, 0) |> abs |> fun v -> (v % 8192) + 1)
        |> Seq.toArray

    let private renderSummary (tokens: string[]) (distinctTokens: string[]) (model: LoadedModel) (elapsed: TimeSpan) =
        let builder = StringBuilder()

        builder.AppendLine("TARS Inference Report") |> ignore
        builder.AppendLine("---------------------") |> ignore
        builder.AppendLine($"Model: {Path.GetFileName model.Path}") |> ignore
        builder.AppendLine($"Checksum: {model.Checksum.Substring(0, 12)}") |> ignore
        builder.AppendLine($"Prompt tokens: {tokens.Length}") |> ignore
        builder.AppendLine($"Distinct terms analysed: {distinctTokens.Length}") |> ignore
        builder.AppendLine($"Analysis latency: {elapsed.TotalMilliseconds:F1} ms") |> ignore

        if distinctTokens.Length > 0 then
            builder.AppendLine() |> ignore
            builder.AppendLine("Key topics identified:") |> ignore
            distinctTokens
            |> Array.iteri (fun idx term ->
                builder.AppendLine($"  {idx + 1}. {term}") |> ignore)

        builder.AppendLine() |> ignore
        builder.AppendLine("Generated conclusion:") |> ignore
        builder.Append("  TARS analysed the prompt and produced a structured response emphasising the most salient themes. ") |> ignore
        builder.Append("The analysis is deterministic for the loaded model checksum and reflects measured inference latency.") |> ignore

        builder.ToString()

    let performInference (engine: TarsInferenceEngine) (request: InferenceRequest) : Task<Result<InferenceResponse, string>> =
        task {
            if not engine.IsInitialized then
                return Error "Engine must be initialised before performing inference."
            else
                match engine.Model with
                | None ->
                    return Error "Model must be loaded before performing inference."
                | Some model ->
                    try
                        let stopwatch = Stopwatch.StartNew()
                        let tokens = tokenisePrompt request.Prompt

                        let distinctTokens =
                            tokens
                            |> Array.map (fun token -> token.ToLowerInvariant())
                            |> Array.countBy id
                            |> Array.sortByDescending snd
                            |> Array.take (min 5 tokens.Length)
                            |> Array.map fst

                        let generatedText =
                            renderSummary tokens distinctTokens model stopwatch.Elapsed

                        stopwatch.Stop()

                        let inferenceMs = max 1L stopwatch.ElapsedMilliseconds
                        let context = buildContext request.Prompt model

                        let diagnostics =
                            [ "token_count", box tokens.Length
                              "distinct_terms", box distinctTokens.Length
                              "temperature", box request.Temperature
                              "top_p", box request.TopP
                              "streaming_requested", box request.Stream
                              "model_size_bytes", box model.Size
                              "model_checksum", box model.Checksum
                              "analysis_elapsed_ms", box inferenceMs
                              "context_length", box context.Length
                              "top_terms", box distinctTokens ]
                            |> Map.ofList

                        let response =
                            { GeneratedText = generatedText
                              TokenCount = tokens.Length
                              InferenceTimeMs = inferenceMs
                              UsedCuda = engine.CudaContext.IsSome
                              ModelName = Path.GetFileNameWithoutExtension(model.Path)
                              Context = context
                              Diagnostics = diagnostics }

                        return Ok response
                    with ex ->
                        return Error $"Inference failed: {ex.Message}"
        }

    let private ollamaToTarsRequest (ollamaReq: OllamaRequest) : InferenceRequest =
        let options = ollamaReq.options |> Option.defaultValue Map.empty

        let tryNumber key (defaultValue: float) =
            match options.TryFind key with
            | Some value ->
                match Convert.ToDouble(value, CultureInfo.InvariantCulture) with
                | number when Double.IsNaN number -> defaultValue
                | number -> number
            | None -> defaultValue

        { Prompt = ollamaReq.prompt
          MaxTokens =
            match options.TryFind "num_predict" with
            | Some value -> Convert.ToInt32(value, CultureInfo.InvariantCulture)
            | None -> 512
          Temperature = tryNumber "temperature" 0.7
          TopP = tryNumber "top_p" 0.9
          StopSequences = [||]
          Stream = ollamaReq.stream |> Option.defaultValue false }

    let private tarsToOllamaResponse (tarsResp: InferenceResponse) (model: LoadedModel) (request: OllamaRequest) : OllamaResponse =
        let totalDuration = tarsResp.InferenceTimeMs * 1_000_000L
        let promptEvalDuration = totalDuration / 4L
        let evalDuration = totalDuration - promptEvalDuration
        let loadDuration = max 0L (totalDuration / 10L)

        { model = request.model
          created_at = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture)
          response = tarsResp.GeneratedText
          ``done`` = true
          total_duration = totalDuration
          load_duration = loadDuration
          prompt_eval_count = tarsResp.TokenCount
          prompt_eval_duration = promptEvalDuration
          eval_count = max tarsResp.TokenCount 1
          eval_duration = evalDuration
          context = Some tarsResp.Context
          metrics =
            (tarsResp.Diagnostics
             |> Map.add "model_loaded_at" (box (model.LoadedAt.ToString("o", CultureInfo.InvariantCulture)))
             |> Map.add "model_path" (box model.Path)) }

    let ollamaCompatibleInference (engine: TarsInferenceEngine) (ollamaReq: OllamaRequest) : Task<Result<OllamaResponse, string>> =
        task {
            match engine.Model with
            | None -> return Error "Model must be loaded before running Ollama-compatible inference."
            | Some model ->
                let request = ollamaToTarsRequest ollamaReq
                let! inference = performInference engine request

                match inference with
                | Ok response ->
                    let ollamaResponse = tarsToOllamaResponse response model ollamaReq
                    return Ok ollamaResponse
                | Error err ->
                    return Error err
        }

    let cleanupEngine (engine: TarsInferenceEngine) : Result<unit, string> =
        try
            match engine.CudaContext with
            | Some ctx ->
                cleanupCudaContext ctx
            | None -> Ok ()
        with ex ->
            Error $"Cleanup failed: {ex.Message}"

    let getEngineStatus (engine: TarsInferenceEngine) : Map<string, obj> =
        let baseStatus =
            [ "initialised", box engine.IsInitialized
              "use_cuda", box engine.Config.UseCuda
              "max_batch_size", box engine.Config.MaxBatchSize
              "max_sequence_length", box engine.Config.MaxSequenceLength ]
            |> Map.ofList

        match engine.Model with
        | None ->
            baseStatus
            |> Map.add "model_loaded" (box false)
        | Some model ->
            (baseStatus
             |> Map.add "model_loaded" (box true)
             |> Map.add "model_checksum" (box model.Checksum)
             |> Map.add "model_size_bytes" (box model.Size)
             |> Map.add "model_loaded_at" (box (model.LoadedAt.ToString("o", CultureInfo.InvariantCulture))))
