namespace Tars.Evolution

open System
open Tars.Core

/// Defines a task generated by the Curriculum Agent
type TaskDefinition =
    {
        Id: Guid
        DifficultyLevel: int
        Goal: string
        Constraints: string list
        /// The validation logic (could be a script, a regex, or a function name)
        ValidationCriteria: string
        Timeout: TimeSpan
        Score: float
    }

/// High-level evaluation result for a task output
type EvaluationResult =
    { Passed: bool
      Confidence: float
      Summary: string
      Issues: string list
      SuggestedFixes: string list
      EvaluatedAt: DateTime }

/// The result of an attempted task execution
type TaskResult =
    {
        TaskId: Guid
        TaskGoal: string
        ExecutorId: AgentId
        Success: bool
        Output: string
        /// The trace of steps taken (for learning)
        ExecutionTrace: string list
        Duration: TimeSpan
        Evaluation: EvaluationResult option
    }

/// Represents the state of the evolutionary loop
type EvolutionState =
    { Generation: int
      CurriculumAgentId: AgentId
      ExecutorAgentId: AgentId
      CompletedTasks: TaskResult list
      CurrentTask: TaskDefinition option
      TaskQueue: TaskDefinition list
      ActiveBeliefs: string list }
