// Webpack configuration for Janus Research UI
// Generated by: devops_engineer_001
// Auto-generated build configuration for F#/Fable/Elmish application

const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = (env, argv) => {
    const isProduction = argv.mode === 'production';
    
    return {
        entry: './src/App.fs.js',
        output: {
            path: path.resolve(__dirname, 'dist'),
            filename: isProduction ? '[name].[contenthash].js' : '[name].js',
            clean: true,
            publicPath: '/'
        },
        
        resolve: {
            extensions: ['.js', '.fs', '.ts'],
            alias: {
                '@': path.resolve(__dirname, 'src')
            }
        },
        
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env']
                        }
                    }
                },
                {
                    test: /\.css$/,
                    use: ['style-loader', 'css-loader']
                },
                {
                    test: /\.(png|jpg|jpeg|gif|svg|ico)$/,
                    type: 'asset/resource',
                    generator: {
                        filename: 'images/[name].[hash][ext]'
                    }
                },
                {
                    test: /\.(woff|woff2|eot|ttf|otf)$/,
                    type: 'asset/resource',
                    generator: {
                        filename: 'fonts/[name].[hash][ext]'
                    }
                }
            ]
        },
        
        plugins: [
            new HtmlWebpackPlugin({
                template: './public/index.html',
                title: 'Janus Research Program - Autonomous UI',
                meta: {
                    'description': 'Autonomous UI for Janus Cosmological Research Program',
                    'keywords': 'janus,cosmology,research,elmish,fable,autonomous-ui',
                    'author': 'TARS Development Department',
                    'viewport': 'width=device-width, initial-scale=1'
                },
                favicon: './public/favicon.ico'
            })
        ],
        
        devServer: {
            static: {
                directory: path.join(__dirname, 'public')
            },
            port: 3000,
            hot: true,
            open: true,
            historyApiFallback: true,
            compress: true,
            client: {
                overlay: {
                    errors: true,
                    warnings: false
                }
            }
        },
        
        optimization: {
            splitChunks: {
                chunks: 'all',
                cacheGroups: {
                    vendor: {
                        test: /[\\/]node_modules[\\/]/,
                        name: 'vendors',
                        chunks: 'all'
                    },
                    fable: {
                        test: /[\\/]fable_modules[\\/]/,
                        name: 'fable',
                        chunks: 'all'
                    }
                }
            }
        },
        
        devtool: isProduction ? 'source-map' : 'eval-source-map',
        
        performance: {
            hints: isProduction ? 'warning' : false,
            maxEntrypointSize: 512000,
            maxAssetSize: 512000
        }
    };
};
