/// Tools for generating and writing markdown documents.
namespace Tars.Tools.Standard

open System
open System.IO
open System.Threading.Tasks
open Tars.Tools

/// Supported document templates
type DocumentTemplate = Design | ADR | Summary | Custom

module DocumentTools =

    /// Parses template type from string
    let parseTemplate (templateStr: string) : DocumentTemplate =
        match templateStr.ToLowerInvariant() with
        | "design" | "designdoc" -> Design
        | "adr" | "decision" -> ADR
        | "summary" | "task" | "session" -> Summary
        | _ -> Custom

    /// Gets the template header for a document type
    let getTemplate (template: DocumentTemplate) (title: string) (date: string) : string =
        match template with
        | Design -> 
            "# " + title + "\n\n" +
            "**Status:** Draft  \n" +
            "**Date:** " + date + "\n\n" +
            "## Overview\n\n_Brief summary._\n\n" +
            "## Context & Problem\n\n_What problem are we solving?_\n\n" +
            "## Goals\n\n- \n\n## Non-Goals\n\n- \n\n" +
            "## Proposed Solution\n\n### Architecture\n\n_Description._\n\n" +
            "## Alternatives\n\n| Option | Pros | Cons |\n|--------|------|------|\n|  |  |  |\n\n" +
            "## Implementation Plan\n\n- [ ] Phase 1\n\n" +
            "## Risks\n\n| Risk | Mitigation |\n|------|------------|\n|  |  |\n\n" +
            "## Open Questions\n\n- [ ] \n"

        | ADR -> 
            "# ADR: " + title + "\n\n" +
            "**Status:** Proposed  \n" +
            "**Date:** " + date + "\n\n" +
            "## Context\n\n_What is the issue?_\n\n" +
            "## Decision\n\n_What change are we proposing?_\n\n" +
            "## Consequences\n\n### Positive\n- \n\n### Negative\n- \n\n" +
            "## Alternatives Considered\n\n- \n"

        | Summary -> 
            "# " + title + "\n\n" +
            "**Date:** " + date + "\n" +
            "**Status:** Complete\n\n" +
            "## Objective\n\n_Main goal._\n\n" +
            "## Accomplishments\n\n### Completed\n- ✅ \n\n### In Progress\n- 🚧 \n\n" +
            "## Key Changes\n\n| File | Change |\n|------|--------|\n|  |  |\n\n" +
            "## Decisions Made\n\n| Decision | Rationale |\n|----------|----------|\n|  |  |\n\n" +
            "## Next Steps\n\n1. \n2. \n"

        | Custom -> 
            "# " + title + "\n\n" +
            "**Date:** " + date + "\n\n" +
            "## Content\n\n_Add content here._\n\n" +
            "---\n*Generated by TARS*\n"

    /// Writes a document to disk
    let writeDocument (path: string) (content: string) =
        let directory = Path.GetDirectoryName(path)
        if not (String.IsNullOrWhiteSpace(directory)) then
            Directory.CreateDirectory(directory) |> ignore
        File.WriteAllText(path, content)
        path

    /// Registered tool for creating markdown documents
    [<TarsToolAttribute("write_document",
        "Creates a structured markdown document from a template. Input JSON: { \"title\": \"Document Title\", \"template\": \"design|adr|summary|custom\", \"path\": \"docs/my_doc.md\", \"content\": \"optional additional content\" }")>]
    let writeDocumentTool (args: string) =
        task {
            try
                use doc = System.Text.Json.JsonDocument.Parse(args)
                let root = doc.RootElement
                
                let title = root.GetProperty("title").GetString()
                let templateStr = 
                    try root.GetProperty("template").GetString() 
                    with _ -> "custom"
                let path = root.GetProperty("path").GetString()
                let additionalContent = 
                    try root.GetProperty("content").GetString() with _ -> ""
                
                let template = parseTemplate templateStr
                let date = DateTime.Now.ToString("yyyy-MM-dd")
                
                let baseContent = getTemplate template title date
                let fullContent = 
                    if String.IsNullOrWhiteSpace(additionalContent) then baseContent
                    else baseContent + "\n\n" + additionalContent
                
                let writtenPath = writeDocument path fullContent
                return Microsoft.FSharp.Core.Result.Ok $"Document created: %s{writtenPath}"
            with ex ->
                return Microsoft.FSharp.Core.Result.Error $"Failed to create document: %s{ex.Message}"
        }

    /// Tool to list available templates
    [<TarsToolAttribute("list_document_templates",
        "Lists all available document templates with descriptions.")>]
    let listTemplates (args: string) =
        let templates = 
            "## Available Document Templates\n\n" +
            "| Template | Description |\n" +
            "|----------|-------------|\n" +
            "| `design` | Technical design proposals |\n" +
            "| `adr` | Architecture Decision Records |\n" +
            "| `summary` | Task/Session Summaries |\n" +
            "| `custom` | Freeform template |\n\n" +
            "### Example\n\n" +
            "```json\n" +
            "{ \"title\": \"My Doc\", \"template\": \"design\", \"path\": \"docs/my_doc.md\" }\n" +
            "```\n"
        Task.FromResult(Microsoft.FSharp.Core.Result.Ok templates)
