namespace Tars.Tools

open System
open System.Threading.Tasks
open Tars.Core

/// Dynamic Tool Factory - creates tools at runtime based on LLM-generated specifications
module ToolFactory =

    /// Tool specification generated by LLM
    type ToolSpec =
        { Name: string
          Description: string
          InputFormat: string
          ExpectedBehavior: string }

    /// Result of tool creation attempt
    type ToolCreationResult =
        | Created of Tool
        | CreationFailed of reason: string

    /// Simple tools that can be dynamically created without code generation
    /// These are "meta-tools" that delegate to existing capabilities
    let private createSimpleTool (spec: ToolSpec) : Tool option =
        match spec.Name.ToLowerInvariant() with
        | "echo"
        | "say"
        | "inform" ->
            Some
                { Name = spec.Name
                  Description = spec.Description
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"[{spec.Name}]: {input}" } }
        | "think"
        | "reason"
        | "analyze" ->
            Some
                { Name = spec.Name
                  Description = "Internal reasoning/thinking step (returns input for self-reflection)"
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"Reasoning: {input}" } }
        | "complete"
        | "done"
        | "finish"
        | "complete_task" ->
            Some
                { Name = spec.Name
                  Description = "Marks the task as complete with the given solution"
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"SOLUTION:\n{input}" } }
        | "propose"
        | "suggest" ->
            Some
                { Name = spec.Name
                  Description = "Proposes a solution or approach"
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"Proposed: {input}" } }
        | "request"
        | "ask" ->
            Some
                { Name = spec.Name
                  Description = "Requests information or action"
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"Request acknowledged: {input}" } }
        | "failure"
        | "error"
        | "fail" ->
            Some
                { Name = spec.Name
                  Description = "Reports a failure or error condition"
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"Failure reported: {input}" } }
        | "query" ->
            Some
                { Name = spec.Name
                  Description = "Queries for information"
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"Query acknowledged: {input}" } }
        | "refuse" ->
            Some
                { Name = spec.Name
                  Description = "Refuses a request"
                  Version = "1.0.0"
                  ParentVersion = None
                  CreatedAt = DateTime.UtcNow
                  Execute = fun input -> async { return Ok $"Refusal acknowledged: {input}" } }
        | _ -> None

    /// Try to create a tool for a missing tool name
    /// This is called when an agent requests a tool that doesn't exist
    let tryCreateTool (toolName: string) (toolInput: string) (context: string list) : ToolCreationResult =
        // Normalize tool name
        let normalizedName = toolName.Trim().ToLowerInvariant()

        // First, try to match against known patterns (speech act performatives)
        let spec =
            { Name = normalizedName
              Description = $"Tool for {normalizedName}"
              InputFormat = "string"
              ExpectedBehavior = "Process input and return result" }

        match createSimpleTool spec with
        | Some tool ->
            printfn $"🔧 ToolFactory: Created dynamic tool '{toolName}'"
            Created tool
        | None ->
            // Fail safely for unknown patterns to avoid aggressive tool creation
            printfn $"⚠️ ToolFactory: Refused to create dynamic tool for unknown pattern '{toolName}'"
            CreationFailed $"Unknown tool pattern '{toolName}'. Only recognized speech acts are supported."

    /// Creates tools for common speech act performatives that get misinterpreted as tool calls
    let createSpeechActTools () : Tool list =
        [ { Name = "REQUEST"
            Description = "Handles REQUEST speech act - acknowledges and processes a request"
            Version = "1.0.0"
            ParentVersion = None
            CreatedAt = DateTime.UtcNow
            Execute = fun input -> async { return Ok $"Request processed: {input}" } }
          { Name = "INFORM"
            Description = "Handles INFORM speech act - acknowledges information"
            Version = "1.0.0"
            ParentVersion = None
            CreatedAt = DateTime.UtcNow
            Execute = fun input -> async { return Ok $"Informed: {input}" } }
          { Name = "PROPOSE"
            Description = "Handles PROPOSE speech act - acknowledges a proposal"
            Version = "1.0.0"
            ParentVersion = None
            CreatedAt = DateTime.UtcNow
            Execute = fun input -> async { return Ok $"Proposal: {input}" } }
          { Name = "FAILURE"
            Description = "Handles FAILURE speech act - reports a failure"
            Version = "1.0.0"
            ParentVersion = None
            CreatedAt = DateTime.UtcNow
            Execute = fun input -> async { return Ok $"Failure: {input}" } }
          { Name = "QUERY"
            Description = "Handles QUERY speech act - processes a query"
            Version = "1.0.0"
            ParentVersion = None
            CreatedAt = DateTime.UtcNow
            Execute = fun input -> async { return Ok $"Query: {input}" } }
          { Name = "REFUSE"
            Description = "Handles REFUSE speech act - acknowledges refusal"
            Version = "1.0.0"
            ParentVersion = None
            CreatedAt = DateTime.UtcNow
            Execute = fun input -> async { return Ok $"Refused: {input}" } }
          { Name = "complete_task"
            Description = "Marks the current task as complete with the final solution"
            Version = "1.0.0"
            ParentVersion = None
            CreatedAt = DateTime.UtcNow
            Execute = fun input -> async { return Ok $"SOLUTION COMPLETE:\n{input}" } } ]
