namespace Tars.Tools

open System
open System.Threading.Tasks
open Tars.Core

/// Dynamic Tool Factory - creates tools at runtime based on LLM-generated specifications
module ToolFactory =

    /// Tool specification generated by LLM
    type ToolSpec =
        { Name: string
          Description: string
          InputFormat: string
          ExpectedBehavior: string }

    /// Result of tool creation attempt
    type ToolCreationResult =
        | Created of Tool
        | CreationFailed of reason: string

    /// Simple tools that can be dynamically created without code generation
    /// These are "meta-tools" that delegate to existing capabilities
    let private createSimpleTool (spec: ToolSpec) : Tool option =
        match spec.Name.ToLowerInvariant() with
        | "echo"
        | "say"
        | "inform" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, spec.Description, (fun input -> async { return Ok $"[{spec.Name}]: {input}" })))
        | "think"
        | "reason"
        | "analyze" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, "Internal reasoning/thinking step (returns input for self-reflection)", (fun input -> async { return Ok $"Reasoning: {input}" })))
        | "complete"
        | "done"
        | "finish"
        | "complete_task" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, "Marks the task as complete with the given solution", (fun input -> async { return Ok $"SOLUTION:\n{input}" })))
        | "propose"
        | "suggest" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, "Proposes a solution or approach", (fun input -> async { return Ok $"Proposed: {input}" })))
        | "request"
        | "ask" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, "Requests information or action", (fun input -> async { return Ok $"Request acknowledged: {input}" })))
        | "failure"
        | "error"
        | "fail" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, "Reports a failure or error condition", (fun input -> async { return Ok $"Failure reported: {input}" })))
        | "query" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, "Queries for information", (fun input -> async { return Ok $"Query acknowledged: {input}" })))
        | "refuse" ->
            Some
                (Tool.InternalCreateMinimal(spec.Name, "Refuses a request", (fun input -> async { return Ok $"Refusal acknowledged: {input}" })))
        | _ -> None

    /// Try to create a tool for a missing tool name
    /// This is called when an agent requests a tool that doesn't exist
    let tryCreateTool (toolName: string) (toolInput: string) (context: string list) : ToolCreationResult =
        // Normalize tool name
        let normalizedName = toolName.Trim().ToLowerInvariant()

        // First, try to match against known patterns (speech act performatives)
        let spec =
            { Name = normalizedName
              Description = $"Tool for {normalizedName}"
              InputFormat = "string"
              ExpectedBehavior = "Process input and return result" }

        match createSimpleTool spec with
        | Some tool ->
            printfn $"🔧 ToolFactory: Created dynamic tool '{toolName}'"
            Created tool
        | None ->
            // Fail safely for unknown patterns to avoid aggressive tool creation
            printfn $"⚠️ ToolFactory: Refused to create dynamic tool for unknown pattern '{toolName}'"
            CreationFailed $"Unknown tool pattern '{toolName}'. Only recognized speech acts are supported."

    /// Creates tools for common speech act performatives that get misinterpreted as tool calls
    let createSpeechActTools () : Tool list =
        [ Tool.InternalCreateMinimal("REQUEST", "Handles REQUEST speech act - acknowledges and processes a request", (fun input -> async { return Ok $"Request processed: {input}" }))
          Tool.InternalCreateMinimal("INFORM", "Handles INFORM speech act - acknowledges information", (fun input -> async { return Ok $"Informed: {input}" }))
          Tool.InternalCreateMinimal("PROPOSE", "Handles PROPOSE speech act - acknowledges a proposal", (fun input -> async { return Ok $"Proposal: {input}" }))
          Tool.InternalCreateMinimal("FAILURE", "Handles FAILURE speech act - reports a failure", (fun input -> async { return Ok $"Failure: {input}" }))
          Tool.InternalCreateMinimal("QUERY", "Handles QUERY speech act - processes a query", (fun input -> async { return Ok $"Query: {input}" }))
          Tool.InternalCreateMinimal("REFUSE", "Handles REFUSE speech act - acknowledges refusal", (fun input -> async { return Ok $"Refused: {input}" }))
          Tool.InternalCreateMinimal("complete_task", "Marks the current task as complete with the final solution", (fun input -> async { return Ok $"SOLUTION COMPLETE:\n{input}" })) ]
