namespace Tars.Cortex

open System
open System.Threading
open Tars.Core
open Tars.Cortex.WoTTypes

/// <summary>
/// Phase 8.4.1: WoT Controller - The cognitive orchestrator for Workflow of Thought.
///
/// Implements the five key controller components:
/// 1. Planner - Breaks goal into sub-goals and seeds initial nodes
/// 2. Generator - Creates candidate thoughts, tool calls, summaries
/// 3. Critic - Evaluates relevance, correctness, risk, policy compliance
/// 4. Router - Decides: expand, merge, rollback, escalate, or finalize
/// 5. Distiller - Compresses subgraph into clean prose or structured JSON
/// </summary>
module WoTController =

    // =========================================================================
    // Router Decision Types
    // =========================================================================

    /// <summary>
    /// Decisions the Router can make during WoT execution.
    /// </summary>
    type RouterDecision =
        | Expand of nodeId: string * reason: string
        | Merge of nodeIds: string list * targetSynthesis: string
        | Rollback of toNodeId: string * reason: string
        | Escalate of nodeId: string * reason: string * urgency: float
        | Finalize of nodeId: string * confidence: float
        | CallTool of toolName: string * args: Map<string, obj>
        | ApplyPolicy of policyName: string * target: string
        | Retry of nodeId: string * maxAttempts: int

    /// <summary>
    /// Context for routing decisions.
    /// </summary>
    type RoutingContext =
        { CurrentNode: WoTNode
          ExecutedNodes: WoTTraceStep list
          RemainingBudget: Budget
          ConstraintScore: float option
          FailedAttempts: Map<string, int>
          Goal: string }

    // =========================================================================
    // Critic Evaluation Types
    // =========================================================================

    /// <summary>
    /// Dimensions the Critic evaluates.
    /// </summary>
    type CriticDimension =
        | Relevance of score: float * reason: string
        | Correctness of score: float * evidence: string list
        | Risk of level: float * factors: string list
        | PolicyCompliance of passed: bool * violations: string list
        | Quality of score: float * aspects: Map<string, float>

    /// <summary>
    /// Complete critique of a node or subgraph.
    /// </summary>
    type Critique =
        { NodeId: string
          Dimensions: CriticDimension list
          OverallScore: float
          Recommendation: RouterDecision
          Reasoning: string
          CritiquedAt: DateTime }

    // =========================================================================
    // Planner Types
    // =========================================================================

    /// <summary>
    /// A sub-goal decomposed by the Planner.
    /// </summary>
    type SubGoal =
        { Id: string
          Description: string
          Priority: int
          Dependencies: string list
          EstimatedComplexity: float
          SuggestedPattern: PatternKind option }

    /// <summary>
    /// A complete plan produced by the Planner.
    /// </summary>
    type PlannerOutput =
        { Goal: string
          SubGoals: SubGoal list
          InitialNodes: WoTNode list
          InitialEdges: WoTEdge list
          EstimatedSteps: int
          EstimatedTokens: int
          Constraints: string list }

    // =========================================================================
    // Generator Types
    // =========================================================================

    /// <summary>
    /// A candidate generated by the Generator.
    /// </summary>
    type Candidate =
        { Id: string
          Node: WoTNode
          Score: float
          Rationale: string
          GeneratedAt: DateTime }

    /// <summary>
    /// Generator output with multiple candidates.
    /// </summary>
    type GeneratorOutput =
        { Candidates: Candidate list
          BestCandidate: Candidate option
          DiversityScore: float }

    // =========================================================================
    // Distiller Types
    // =========================================================================

    /// <summary>
    /// Format for distilled output.
    /// </summary>
    type DistillFormat =
        | Prose
        | Markdown
        | Json
        | Triples

    /// <summary>
    /// Distilled output from a subgraph.
    /// </summary>
    type DistilledOutput =
        { Content: string
          Format: DistillFormat
          SourceNodes: string list
          Confidence: float
          KeyInsights: string list
          DistilledAt: DateTime }

    // =========================================================================
    // Service Interfaces (Phase 8.4.2-8.4.6)
    // =========================================================================

    /// <summary>
    /// Result from an LLM reasoning call.
    /// </summary>
    type LlmReasoningResult =
        { Response: string
          TokensUsed: int
          Confidence: float
          Model: string
          DurationMs: int64 }

    /// <summary>
    /// Service for LLM-powered reasoning (Phase 8.4.2).
    /// </summary>
    type ILlmReasoningService =
        abstract member ReasonAsync:
            prompt: string * context: string option * maxTokens: int option -> Async<Result<LlmReasoningResult, string>>

        abstract member GenerateCandidatesAsync: prompt: string * count: int -> Async<Result<string list, string>>

        abstract member CritiqueAsync:
            content: string * criteria: string list -> Async<Result<Map<string, float>, string>>

    /// <summary>
    /// Result from a tool execution.
    /// </summary>
    type ToolExecutionResult =
        { Output: string
          Success: bool
          DurationMs: int64
          Artifacts: string list }

    /// <summary>
    /// Service for tool execution (Phase 8.4.2).
    /// </summary>
    type IToolExecutionService =
        abstract member ExecuteAsync:
            toolName: string * args: Map<string, obj> -> Async<Result<ToolExecutionResult, string>>

        abstract member ListAvailableTools: unit -> string list
        abstract member GetToolDescription: toolName: string -> string option

    /// <summary>
    /// Knowledge operation type.
    /// </summary>
    type KnowledgeOp =
        | ReadBelief of subject: string * predicate: string
        | WriteBelief of subject: string * predicate: string * object: string * confidence: float
        | QueryTriples of query: string
        | AssertFact of triple: (string * string * string)
        | RetractFact of triple: (string * string * string)
        | SearchKnowledge of query: string * limit: int

    /// <summary>
    /// Service for knowledge ledger operations (Phase 8.4.3).
    /// </summary>
    type IKnowledgeLedgerService =
        abstract member ExecuteOpAsync: op: KnowledgeOp -> Async<Result<string, string>>
        abstract member GetRelevantKnowledge: topic: string * limit: int -> Async<string list>
        abstract member LogInsight: insight: string * source: string -> Async<unit>

    /// <summary>
    /// Human escalation request.
    /// </summary>
    type EscalationRequest =
        { NodeId: string
          Reason: string
          Urgency: float
          Context: string
          Options: string list
          DefaultOption: string option }

    /// <summary>
    /// Human escalation response.
    /// </summary>
    type EscalationResponse =
        { SelectedOption: string option
          FreeformInput: string option
          Approved: bool
          Timestamp: DateTime }

    /// <summary>
    /// Service for human-in-the-loop escalation (Phase 8.4.4).
    /// </summary>
    type IHumanEscalationService =
        abstract member RequestInputAsync: request: EscalationRequest -> Async<EscalationResponse>
        abstract member NotifyAsync: message: string * level: string -> Async<unit>
        abstract member ConfirmContinue: message: string -> Async<bool>

    /// <summary>
    /// Validation result.
    /// </summary>
    type ValidationResult =
        { Passed: bool
          Score: float
          Issues: string list
          Suggestions: string list
          ValidatorName: string }

    /// <summary>
    /// Service for external validation (Phase 8.4.5).
    /// </summary>
    /// Service for external validation (Phase 8.4.5).
    /// </summary>
    type IValidationService =
        abstract member ValidateAsync:
            content: string * validationType: string -> Async<Result<ValidationResult, string>>

        abstract member ValidateCodeAsync: code: string * language: string -> Async<Result<ValidationResult, string>>
        abstract member ValidateFactsAsync: claims: string list -> Async<Result<ValidationResult, string>>

        abstract member ValidateInvariantsAsync:
            content: string * invariants: WoTInvariant list -> Async<Result<ValidationResult, string>>

    /// <summary>
    /// Combined services for the integrated controller.
    /// </summary>
    type ControllerServices =
        { LlmService: ILlmReasoningService option
          ToolService: IToolExecutionService option
          KnowledgeService: IKnowledgeLedgerService option
          EscalationService: IHumanEscalationService option
          ValidationService: IValidationService option }

        static member Empty =
            { LlmService = None
              ToolService = None
              KnowledgeService = None
              EscalationService = None
              ValidationService = None }


    // =========================================================================
    // Controller State
    // =========================================================================

    /// <summary>
    /// Complete state of the WoT Controller.
    /// </summary>
    type ControllerState =
        { Plan: WoTPlan
          ExecutedSteps: WoTTraceStep list
          PendingNodes: string list
          ActiveNode: string option
          Critiques: Map<string, Critique>
          Candidates: Candidate list
          Decisions: (DateTime * RouterDecision) list
          Budget: Budget
          StartedAt: DateTime
          LastActivity: DateTime
          EscalationsPending: (string * string * float) list // nodeId, reason, urgency
          HumanInputRequired: bool }

    // =========================================================================
    // Planner Component
    // =========================================================================

    /// <summary>
    /// The Planner decomposes goals into sub-goals and seeds initial nodes.
    /// </summary>
    module Planner =

        /// <summary>
        /// Decompose a goal into sub-goals using heuristic analysis.
        /// </summary>
        let decompose (goal: string) : SubGoal list =
            // Identify complexity markers
            let hasMultipleParts =
                goal.Contains(" and ") || goal.Contains(" then ") || goal.Contains(";")

            let requiresResearch =
                goal.Contains("analyze")
                || goal.Contains("research")
                || goal.Contains("investigate")

            let requiresImplementation =
                goal.Contains("implement") || goal.Contains("create") || goal.Contains("build")

            let requiresVerification =
                goal.Contains("verify") || goal.Contains("validate") || goal.Contains("test")

            // Generate sub-goals based on analysis
            [ if requiresResearch then
                  yield
                      { Id = "sg_research"
                        Description = $"Research: Gather information about {goal}"
                        Priority = 1
                        Dependencies = []
                        EstimatedComplexity = 0.3
                        SuggestedPattern = Some GraphOfThoughts }

              if requiresImplementation then
                  yield
                      { Id = "sg_implement"
                        Description = $"Implement: Execute the core task"
                        Priority = 2
                        Dependencies = if requiresResearch then [ "sg_research" ] else []
                        EstimatedComplexity = 0.5
                        SuggestedPattern = Some ReAct }

              if requiresVerification then
                  yield
                      { Id = "sg_verify"
                        Description = $"Verify: Validate the result"
                        Priority = 3
                        Dependencies = if requiresImplementation then [ "sg_implement" ] else []
                        EstimatedComplexity = 0.2
                        SuggestedPattern = Some ChainOfThought }

              if not requiresResearch && not requiresImplementation && not requiresVerification then
                  yield
                      { Id = "sg_main"
                        Description = goal
                        Priority = 1
                        Dependencies = []
                        EstimatedComplexity = 0.5
                        SuggestedPattern = Some ChainOfThought } ]

        /// <summary>
        /// Seed initial WoT nodes from sub-goals.
        /// </summary>
        let seedNodes (subGoals: SubGoal list) : WoTNode list * WoTEdge list =
            let nodes =
                subGoals
                |> List.map (fun sg ->
                    { Id = $"plan_{sg.Id}"
                      Kind = Reason
                      Payload =
                        { Prompt = sg.Description
                          Hint = Some Smart }
                        :> obj
                      Metadata =
                        { Label = Some sg.Description
                          Tags = [ "planner"; "subgoal" ]
                          Extra = Map.empty } })

            let edges =
                subGoals
                |> List.collect (fun sg ->
                    sg.Dependencies
                    |> List.map (fun dep ->
                        { From = $"plan_{dep}"
                          To = $"plan_{sg.Id}"
                          Label = Some "depends_on"
                          Confidence = Some 1.0 }))

            (nodes, edges)

        /// <summary>
        /// Create a complete plan for a goal.
        /// </summary>
        let createPlan (goal: string) (budget: Budget) : PlannerOutput =
            let subGoals = decompose goal
            let (nodes, edges) = seedNodes subGoals

            let estimatedSteps =
                subGoals
                |> List.sumBy (fun sg ->
                    match sg.SuggestedPattern with
                    | Some ChainOfThought -> 3
                    | Some ReAct -> 5
                    | Some GraphOfThoughts -> 6
                    | Some TreeOfThoughts -> 8
                    | _ -> 3)

            { Goal = goal
              SubGoals = subGoals
              InitialNodes = nodes
              InitialEdges = edges
              EstimatedSteps = estimatedSteps
              EstimatedTokens = estimatedSteps * 500 // ~500 tokens per step
              Constraints = [ "max_retries:3"; "require_verification" ] }

    // =========================================================================
    // Generator Component
    // =========================================================================

    /// <summary>
    /// The Generator creates candidate thoughts, tool calls, and summaries.
    /// </summary>
    module Generator =

        /// <summary>
        /// Generate candidate thought nodes for expansion.
        /// </summary>
        let generateThoughts (prompt: string) (count: int) : Candidate list =
            // Generate diverse thought candidates
            let variations =
                [ "Let me analyze this step by step:"
                  "Breaking this down into components:"
                  "Considering the key factors:"
                  "From first principles:"
                  "Looking at this from multiple angles:" ]

            variations
            |> List.take (min count variations.Length)
            |> List.mapi (fun i variation ->
                let guidPart = Guid.NewGuid().ToString("N").Substring(0, 8)
                let id = sprintf "thought_%s" guidPart
                let genId = sprintf "gen_%d" i
                let promptText = sprintf "%s %s" variation prompt

                { Id = id
                  Node =
                    { Id = genId
                      Kind = Reason
                      Payload =
                        { Prompt = promptText
                          Hint = Some Smart }
                        :> obj
                      Metadata =
                        { Label = Some variation
                          Tags = [ "generated"; "thought" ]
                          Extra = Map.empty } }
                  Score = 1.0 - (float i * 0.1) // Decreasing scores
                  Rationale = sprintf "Approach: %s" variation
                  GeneratedAt = DateTime.UtcNow })

        /// <summary>
        /// Generate tool call candidates.
        /// </summary>
        let generateToolCalls (context: string) (availableTools: string list) : Candidate list =
            availableTools
            |> List.mapi (fun i tool ->
                let guidPart = Guid.NewGuid().ToString("N").Substring(0, 8)
                let id = sprintf "tool_%s" guidPart
                let toolId = sprintf "tool_%d" i
                let labelText = sprintf "Call %s" tool

                { Id = id
                  Node =
                    { Id = toolId
                      Kind = Tool
                      Payload = { Tool = tool; Args = Map.empty } :> obj
                      Metadata =
                        { Label = Some labelText
                          Tags = [ "generated"; "tool" ]
                          Extra = Map.empty } }
                  Score = 0.5
                  Rationale = sprintf "Tool '%s' may help with: %s" tool context
                  GeneratedAt = DateTime.UtcNow })

        /// <summary>
        /// Generate synthesis candidates from multiple inputs.
        /// </summary>
        let generateSynthesis (inputs: string list) : Candidate list =
            let inputSummary = inputs |> String.concat "; "
            let guidPart = Guid.NewGuid().ToString("N").Substring(0, 8)
            let id = sprintf "synth_%s" guidPart
            let promptText = sprintf "Synthesize these insights: %s" inputSummary

            [ { Id = id
                Node =
                  { Id = "synthesis"
                    Kind = Reason
                    Payload =
                      { Prompt = promptText
                        Hint = Some Smart }
                      :> obj
                    Metadata =
                      { Label = Some "Synthesis"
                        Tags = [ "synthesis" ]
                        Extra = Map.empty } }
                Score = 0.9
                Rationale = "Combine multiple perspectives into coherent output"
                GeneratedAt = DateTime.UtcNow } ]

        /// <summary>
        /// Generate best candidate set with diversity.
        /// </summary>
        let generate (prompt: string) (count: int) (includeTools: string list) : GeneratorOutput =
            let thoughts = generateThoughts prompt count
            let tools = generateToolCalls prompt includeTools
            let all = thoughts @ tools |> List.sortByDescending (fun c -> c.Score)

            let diversityScore =
                let kinds = all |> List.map (fun c -> c.Node.Kind) |> List.distinct |> List.length
                float kinds / float (all.Length |> max 1)

            { Candidates = all
              BestCandidate = all |> List.tryHead
              DiversityScore = diversityScore }

    // =========================================================================
    // Critic Component
    // =========================================================================

    /// <summary>
    /// The Critic evaluates relevance, correctness, risk, and policy compliance.
    /// </summary>
    module Critic =

        /// <summary>
        /// Evaluate a node's relevance to the goal.
        /// </summary>
        let evaluateRelevance (node: WoTNode) (goal: string) : CriticDimension =
            // Simple keyword overlap for relevance
            let goalWords =
                goal.ToLower().Split([| ' '; ','; '.'; ';' |], StringSplitOptions.RemoveEmptyEntries)
                |> Set.ofArray

            let nodeContent =
                match node.Payload with
                | :? ReasonPayload as p -> p.Prompt
                | :? ToolPayload as p -> p.Tool
                | _ -> ""

            let nodeWords =
                nodeContent.ToLower().Split([| ' '; ','; '.'; ';' |], StringSplitOptions.RemoveEmptyEntries)
                |> Set.ofArray

            let overlap = Set.intersect goalWords nodeWords |> Set.count |> float
            let score = (overlap / float (Set.count goalWords |> max 1)) |> min 1.0

            Relevance(score, $"Keyword overlap: {overlap} of {Set.count goalWords}")

        /// <summary>
        /// Evaluate risk factors.
        /// </summary>
        let evaluateRisk (node: WoTNode) : CriticDimension =
            let factors = ResizeArray<string>()
            let mutable level = 0.0

            match node.Kind with
            | Tool ->
                factors.Add("External side effects possible")
                level <- level + 0.3
            | Memory ->
                factors.Add("State modification")
                level <- level + 0.2
            | _ -> ()

            // Check for dangerous patterns in payloads
            match node.Payload with
            | :? ToolPayload as p ->
                if p.Tool.Contains("delete") || p.Tool.Contains("remove") then
                    factors.Add("Destructive operation")
                    level <- level + 0.4

                if p.Tool.Contains("execute") || p.Tool.Contains("run") then
                    factors.Add("Code execution")
                    level <- level + 0.3
            | _ -> ()

            Risk(level |> min 1.0, factors |> Seq.toList)

        /// <summary>
        /// Evaluate policy compliance.
        /// </summary>
        let evaluatePolicyCompliance (node: WoTNode) (policies: string list) : CriticDimension =
            // Simple policy checks
            let violations = ResizeArray<string>()

            policies
            |> List.iter (fun policy ->
                match policy with
                | "require_tool_confirmation" when node.Kind = Tool ->
                    // This would trigger human review
                    ()
                | "max_tokens" ->
                    // Check token budget
                    ()
                | _ -> ())

            PolicyCompliance(violations.Count = 0, violations |> Seq.toList)

        /// <summary>
        /// Create a complete critique of a node.
        /// </summary>
        let critique (node: WoTNode) (goal: string) (policies: string list) : Critique =
            let dimensions =
                [ evaluateRelevance node goal
                  evaluateRisk node
                  evaluatePolicyCompliance node policies ]

            // Calculate overall score
            let scores =
                dimensions
                |> List.choose (fun d ->
                    match d with
                    | Relevance(s, _) -> Some s
                    | Quality(s, _) -> Some s
                    | Risk(r, _) -> Some(1.0 - r) // Invert risk
                    | PolicyCompliance(passed, _) -> Some(if passed then 1.0 else 0.0)
                    | Correctness(s, _) -> Some s)

            let overall = if scores.IsEmpty then 0.5 else scores |> List.average

            let recommendation =
                if overall < 0.3 then Rollback(node.Id, "Low quality score")
                elif overall < 0.6 then Retry(node.Id, 2)
                elif overall >= 0.9 then Finalize(node.Id, overall)
                else Expand(node.Id, "Continue exploration")

            { NodeId = node.Id
              Dimensions = dimensions
              OverallScore = overall
              Recommendation = recommendation
              Reasoning = $"Evaluated {dimensions.Length} dimensions, overall score: {overall:F2}"
              CritiquedAt = DateTime.UtcNow }

    // =========================================================================
    // Router Component
    // =========================================================================

    /// <summary>
    /// The Router decides: expand, merge, rollback, escalate, or finalize.
    /// </summary>
    module Router =

        /// <summary>
        /// Analyze the current state and make a routing decision.
        /// </summary>
        let decide (context: RoutingContext) (critique: Critique option) : RouterDecision =
            let failCount =
                context.FailedAttempts
                |> Map.tryFind context.CurrentNode.Id
                |> Option.defaultValue 0

            // Check for excessive failures
            if failCount >= 3 then
                Escalate(context.CurrentNode.Id, "Max retries exceeded", 0.8)

            // Use critique if available
            elif critique.IsSome then
                critique.Value.Recommendation

            // Check budget
            elif context.RemainingBudget.MaxTokens.IsSome then
                match context.RemainingBudget.MaxTokens with
                | Some tokens when tokens < 1000<token> -> Finalize(context.CurrentNode.Id, 0.6)
                | _ -> Expand(context.CurrentNode.Id, "Budget available")

            // Default: continue
            else
                Expand(context.CurrentNode.Id, "Default expansion")

        /// <summary>
        /// Check if human escalation is needed.
        /// </summary>
        let needsHumanInput (decision: RouterDecision) : bool =
            match decision with
            | Escalate _ -> true
            | _ -> false

        /// <summary>
        /// Get a human-readable description of a decision.
        /// </summary>
        let describeDecision (decision: RouterDecision) : string =
            match decision with
            | Expand(nodeId, reason) -> sprintf "EXPAND: Continue from '%s' - %s" nodeId reason
            | Merge(nodeIds, target) ->
                let joined = nodeIds |> String.concat ", "
                sprintf "MERGE: Combine [%s] into '%s'" joined target
            | Rollback(toNodeId, reason) -> sprintf "ROLLBACK: Return to '%s' - %s" toNodeId reason
            | Escalate(nodeId, reason, urgency) ->
                sprintf "ESCALATE: Need human review at '%s' (urgency: %.2f) - %s" nodeId urgency reason
            | Finalize(nodeId, confidence) ->
                sprintf "FINALIZE: Mark '%s' as complete (confidence: %.2f)" nodeId confidence
            | CallTool(tool, _) -> sprintf "TOOL: Execute '%s'" tool
            | ApplyPolicy(policy, target) -> sprintf "POLICY: Apply '%s' to '%s'" policy target
            | Retry(nodeId, attempts) -> sprintf "RETRY: Retry '%s' (up to %d attempts)" nodeId attempts

    // =========================================================================
    // Distiller Component
    // =========================================================================

    /// <summary>
    /// The Distiller compresses subgraphs into clean prose or structured JSON.
    /// </summary>
    module Distiller =

        /// <summary>
        /// Extract key insights from trace steps.
        /// </summary>
        let extractInsights (steps: WoTTraceStep list) : string list =
            steps
            |> List.choose (fun step ->
                step.Output
                |> Option.bind (fun o ->
                    if o.Length > 50 then Some(o.Substring(0, 50) + "...")
                    elif o.Length > 0 then Some o
                    else None))
            |> List.distinct
            |> List.truncate 5

        /// <summary>
        /// Distill trace steps into prose.
        /// </summary>
        let toProse (steps: WoTTraceStep list) (goal: string) : DistilledOutput =
            let insights = extractInsights steps

            let successfulSteps =
                steps
                |> List.filter (fun s ->
                    match s.Status with
                    | Completed _ -> true
                    | _ -> false)

            let insightLines =
                insights
                |> List.mapi (fun i insight -> sprintf "%d. %s" (i + 1) insight)
                |> String.concat "\n"

            let content =
                sprintf
                    "## Summary\nGoal: %s\nSteps completed: %d of %d\n\n### Key Insights\n%s\n"
                    goal
                    successfulSteps.Length
                    steps.Length
                    insightLines

            { Content = content
              Format = Prose
              SourceNodes = steps |> List.map (fun s -> s.NodeId)
              Confidence = float successfulSteps.Length / float (steps.Length |> max 1)
              KeyInsights = insights
              DistilledAt = DateTime.UtcNow }

        /// <summary>
        /// Distill trace steps into JSON.
        /// </summary>
        let toJson (steps: WoTTraceStep list) (goal: string) : DistilledOutput =
            let insights = extractInsights steps

            let successfulSteps =
                steps
                |> List.filter (fun s ->
                    match s.Status with
                    | Completed _ -> true
                    | _ -> false)

            let insightsJson =
                insights
                |> List.map (fun i -> sprintf "\"%s\"" (i.Replace("\"", "\\\"")))
                |> String.concat ", "

            let content =
                sprintf
                    "{\"goal\": \"%s\", \"stepsCompleted\": %d, \"totalSteps\": %d, \"insights\": [%s]}"
                    (goal.Replace("\"", "\\\""))
                    successfulSteps.Length
                    steps.Length
                    insightsJson

            { Content = content
              Format = Json
              SourceNodes = steps |> List.map (fun s -> s.NodeId)
              Confidence = float successfulSteps.Length / float (steps.Length |> max 1)
              KeyInsights = insights
              DistilledAt = DateTime.UtcNow }

        /// <summary>
        /// Distill trace steps into knowledge triples.
        /// </summary>
        let toTriples (steps: WoTTraceStep list) : DistilledOutput =
            let triples =
                steps
                |> List.collect (fun step ->
                    match step.Output with
                    | Some output when output.Length > 0 ->
                        [ ($"step:{step.NodeId}", "produced", output.Substring(0, min 100 output.Length)) ]
                    | _ -> [])

            let content =
                triples |> List.map (fun (s, p, o) -> $"{s} | {p} | {o}") |> String.concat "\n"

            { Content = content
              Format = Triples
              SourceNodes = steps |> List.map (fun s -> s.NodeId)
              Confidence = float triples.Length / float (steps.Length |> max 1)
              KeyInsights = triples |> List.map (fun (s, _, _) -> s) |> List.distinct
              DistilledAt = DateTime.UtcNow }

        /// <summary>
        /// Distill steps to the specified format.
        /// </summary>
        let distill (steps: WoTTraceStep list) (goal: string) (format: DistillFormat) : DistilledOutput =
            match format with
            | Prose -> toProse steps goal
            | Markdown -> toProse steps goal // Same as prose for now
            | Json -> toJson steps goal
            | Triples -> toTriples steps

    // =========================================================================
    // Controller Orchestration
    // =========================================================================

    /// <summary>
    /// Initialize controller state for a goal.
    /// </summary>
    let init (goal: string) (budget: Budget) : ControllerState =
        let plannerOutput = Planner.createPlan goal budget

        let plan =
            { Id = Guid.NewGuid()
              Nodes = plannerOutput.InitialNodes
              Edges = plannerOutput.InitialEdges
              EntryNode =
                plannerOutput.InitialNodes
                |> List.tryHead
                |> Option.map (fun n -> n.Id)
                |> Option.defaultValue ""
              Metadata =
                { Kind = WorkflowOfThought
                  SourceGoal = goal
                  CompiledAt = DateTime.UtcNow
                  EstimatedTokens = Some plannerOutput.EstimatedTokens
                  EstimatedSteps = Some plannerOutput.EstimatedSteps }
              Policy = plannerOutput.Constraints }

        { Plan = plan
          ExecutedSteps = []
          PendingNodes = plannerOutput.InitialNodes |> List.map (fun n -> n.Id)
          ActiveNode = Some plan.EntryNode
          Critiques = Map.empty
          Candidates = []
          Decisions = []
          Budget = budget
          StartedAt = DateTime.UtcNow
          LastActivity = DateTime.UtcNow
          EscalationsPending = []
          HumanInputRequired = false }

    /// <summary>
    /// Execute one step of the controller loop.
    /// </summary>
    let step (state: ControllerState) : ControllerState * RouterDecision option =
        match state.ActiveNode with
        | None ->
            // No active node - finalize
            (state, Some(Finalize("", 1.0)))

        | Some nodeId ->
            // Find the current node
            let nodeOpt = state.Plan.Nodes |> List.tryFind (fun n -> n.Id = nodeId)

            match nodeOpt with
            | None ->
                // Node not found, move to next
                let remaining = state.PendingNodes |> List.filter (fun id -> id <> nodeId)
                let newActive = remaining |> List.tryHead

                ({ state with
                    PendingNodes = remaining
                    ActiveNode = newActive
                    LastActivity = DateTime.UtcNow },
                 None)

            | Some node ->
                // Critique the current node
                let critique = Critic.critique node state.Plan.Metadata.SourceGoal state.Plan.Policy

                // Create routing context
                let context =
                    { CurrentNode = node
                      ExecutedNodes = state.ExecutedSteps
                      RemainingBudget = state.Budget
                      ConstraintScore = None
                      FailedAttempts =
                        state.ExecutedSteps
                        |> List.filter (fun s ->
                            match s.Status with
                            | Failed _ -> true
                            | _ -> false)
                        |> List.groupBy (fun s -> s.NodeId)
                        |> List.map (fun (id, steps) -> (id, steps.Length))
                        |> Map.ofList
                      Goal = state.Plan.Metadata.SourceGoal }

                // Make routing decision
                let decision = Router.decide context (Some critique)

                // Update state based on decision
                let needsHuman = Router.needsHumanInput decision

                let newState =
                    { state with
                        Critiques = state.Critiques |> Map.add nodeId critique
                        Decisions = (DateTime.UtcNow, decision) :: state.Decisions
                        HumanInputRequired = needsHuman
                        EscalationsPending =
                            match decision with
                            | Escalate(id, reason, urgency) -> (id, reason, urgency) :: state.EscalationsPending
                            | _ -> state.EscalationsPending
                        LastActivity = DateTime.UtcNow }

                (newState, Some decision)

    /// <summary>
    /// Run the full controller loop until complete or escalation.
    /// </summary>
    let run (state: ControllerState) (maxSteps: int) : ControllerState * DistilledOutput =
        let rec loop currentState stepCount =
            if stepCount >= maxSteps then
                currentState
            elif currentState.HumanInputRequired then
                currentState
            elif currentState.ActiveNode.IsNone then
                currentState
            else
                let (newState, decision) = step currentState

                match decision with
                | Some(Finalize _) -> newState
                | Some(Escalate _) -> newState
                | _ -> loop newState (stepCount + 1)

        let finalState = loop state 0

        let distilled =
            Distiller.distill finalState.ExecutedSteps state.Plan.Metadata.SourceGoal Prose

        (finalState, distilled)

    // =========================================================================
    // Integrated Runner (Phase 8.4.2-8.4.6)
    // =========================================================================

    /// <summary>
    /// Integrated runner that uses all services for full WoT execution.
    /// </summary>
    module IntegratedRunner =

        /// <summary>
        /// Execute a Reason node using the LLM service.
        /// </summary>
        let private executeReasonNode
            (services: ControllerServices)
            (node: WoTNode)
            (goal: string)
            (context: string list)
            : Async<WoTTraceStep> =
            async {
                let startTime = DateTime.UtcNow
                let sw = System.Diagnostics.Stopwatch.StartNew()

                let prompt =
                    sprintf
                        "Goal: %s\n\nTask: %s\n\nContext:\n%s\n\nProvide a thoughtful response:"
                        goal
                        node.Id
                        (context |> String.concat "\n")

                match services.LlmService with
                | Some llm ->
                    let! result = llm.ReasonAsync(prompt, Some(context |> String.concat "\n"), Some 2000)
                    sw.Stop()

                    match result with
                    | Result.Ok res ->
                        return
                            { NodeId = node.Id
                              NodeType = "Reason"
                              StartedAt = startTime
                              Status = NodeStatus.Completed(res.Response, sw.ElapsedMilliseconds)
                              Input = Some prompt
                              Output = Some res.Response
                              Confidence = Some res.Confidence
                              TokensUsed = Some res.TokensUsed }
                    | Result.Error err ->
                        return
                            { NodeId = node.Id
                              NodeType = "Reason"
                              StartedAt = startTime
                              Status = NodeStatus.Failed(err, sw.ElapsedMilliseconds)
                              Input = Some prompt
                              Output = None
                              Confidence = None
                              TokensUsed = None }
                | None ->
                    sw.Stop()
                    // Fallback to heuristic response
                    let heuristicResponse =
                        sprintf "[Heuristic] Processing node %s for goal: %s" node.Id goal

                    return
                        { NodeId = node.Id
                          NodeType = "Reason"
                          StartedAt = startTime
                          Status = NodeStatus.Completed(heuristicResponse, sw.ElapsedMilliseconds)
                          Input = Some prompt
                          Output = Some heuristicResponse
                          Confidence = Some 0.5
                          TokensUsed = Some 0 }
            }

        /// <summary>
        /// Execute a Tool node using the tool service.
        /// </summary>
        let private executeToolNode
            (services: ControllerServices)
            (node: WoTNode)
            (toolName: string)
            (args: Map<string, obj>)
            : Async<WoTTraceStep> =
            async {
                let startTime = DateTime.UtcNow
                let sw = System.Diagnostics.Stopwatch.StartNew()

                match services.ToolService with
                | Some toolSvc ->
                    let! result = toolSvc.ExecuteAsync(toolName, args)
                    sw.Stop()

                    match result with
                    | Result.Ok res ->
                        return
                            { NodeId = node.Id
                              NodeType = "Tool"
                              StartedAt = startTime
                              Status =
                                if res.Success then
                                    NodeStatus.Completed(res.Output, res.DurationMs)
                                else
                                    NodeStatus.Failed(res.Output, res.DurationMs)
                              Input = Some(sprintf "Tool: %s, Args: %A" toolName args)
                              Output = Some res.Output
                              Confidence = if res.Success then Some 1.0 else Some 0.0
                              TokensUsed = None }
                    | Result.Error err ->
                        return
                            { NodeId = node.Id
                              NodeType = "Tool"
                              StartedAt = startTime
                              Status = NodeStatus.Failed(err, sw.ElapsedMilliseconds)
                              Input = Some(sprintf "Tool: %s" toolName)
                              Output = None
                              Confidence = None
                              TokensUsed = None }
                | None ->
                    sw.Stop()
                    let mockOutput = sprintf "[Mock] Tool %s executed with args %A" toolName args

                    return
                        { NodeId = node.Id
                          NodeType = "Tool"
                          StartedAt = startTime
                          Status = NodeStatus.Completed(mockOutput, sw.ElapsedMilliseconds)
                          Input = Some(sprintf "Tool: %s" toolName)
                          Output = Some mockOutput
                          Confidence = Some 0.5
                          TokensUsed = None }
            }

        /// <summary>
        /// Execute a Knowledge operation.
        /// </summary>
        let private executeKnowledgeOp
            (services: ControllerServices)
            (op: MemoryOp)
            (nodeId: string)
            : Async<WoTTraceStep> =
            async {
                let startTime = DateTime.UtcNow
                let sw = System.Diagnostics.Stopwatch.StartNew()

                match services.KnowledgeService with
                | Some kSvc ->
                    let knowledgeOp =
                        match op with
                        | MemoryOp.Query sparql -> QueryTriples(sparql)
                        | MemoryOp.Assert(s, p, o) -> AssertFact(s, p, o)
                        | MemoryOp.Retract(s, p, o) -> RetractFact(s, p, o)
                        | MemoryOp.Search(emb, k) -> SearchKnowledge("vector_search_placeholder", k)

                    let! result = kSvc.ExecuteOpAsync(knowledgeOp)
                    sw.Stop()

                    match result with
                    | Result.Ok output ->
                        return
                            { NodeId = nodeId
                              NodeType = "Memory"
                              StartedAt = startTime
                              Status = NodeStatus.Completed(output, sw.ElapsedMilliseconds)
                              Input = Some(sprintf "MemoryOp: %A" op)
                              Output = Some output
                              Confidence = Some 1.0
                              TokensUsed = None }
                    | Result.Error err ->
                        return
                            { NodeId = nodeId
                              NodeType = "Memory"
                              StartedAt = startTime
                              Status = NodeStatus.Failed(err, sw.ElapsedMilliseconds)
                              Input = Some(sprintf "MemoryOp: %A" op)
                              Output = None
                              Confidence = None
                              TokensUsed = None }
                | None ->
                    sw.Stop()
                    let mockOutput = sprintf "[Mock] Knowledge op: %A" op

                    return
                        { NodeId = nodeId
                          NodeType = "Memory"
                          StartedAt = startTime
                          Status = NodeStatus.Completed(mockOutput, sw.ElapsedMilliseconds)
                          Input = Some(sprintf "MemoryOp: %A" op)
                          Output = Some mockOutput
                          Confidence = Some 0.5
                          TokensUsed = None }
            }

        /// <summary>
        /// Handle human escalation.
        /// </summary>
        let private handleEscalation
            (services: ControllerServices)
            (nodeId: string)
            (reason: string)
            (urgency: float)
            (context: string)
            : Async<EscalationResponse> =
            async {
                match services.EscalationService with
                | Some escSvc ->
                    let request =
                        { NodeId = nodeId
                          Reason = reason
                          Urgency = urgency
                          Context = context
                          Options = [ "continue"; "skip"; "abort"; "modify" ]
                          DefaultOption = Some "continue" }

                    return! escSvc.RequestInputAsync(request)
                | None ->
                    // Auto-approve if no escalation service
                    return
                        { SelectedOption = Some "continue"
                          FreeformInput = None
                          Approved = true
                          Timestamp = DateTime.UtcNow }
            }

        /// <summary>
        /// Execute validation on content.
        /// </summary>
        let private executeValidation
            (services: ControllerServices)
            (nodeId: string)
            (content: string)
            (invariants: WoTInvariant list)
            : Async<WoTTraceStep> =
            async {
                let startTime = DateTime.UtcNow
                let sw = System.Diagnostics.Stopwatch.StartNew()

                match services.ValidationService with
                | Some valSvc ->
                    let! result =
                        if invariants.IsEmpty then
                            valSvc.ValidateAsync(content, "general")
                        else
                            valSvc.ValidateInvariantsAsync(content, invariants)

                    sw.Stop()

                    match result with
                    | Ok res ->
                        let output =
                            sprintf
                                "Validation %s: %s (Score: %.2f)"
                                (if res.Passed then "PASSED" else "FAILED")
                                res.ValidatorName
                                res.Score

                        return
                            { NodeId = nodeId
                              NodeType = "Validate"
                              StartedAt = startTime
                              Status =
                                if res.Passed then
                                    NodeStatus.Completed(output, sw.ElapsedMilliseconds)
                                else
                                    NodeStatus.Failed(output, sw.ElapsedMilliseconds)
                              Input = Some content
                              Output = Some output
                              Confidence = Some res.Score
                              TokensUsed = None }
                    | Result.Error err ->
                        return
                            { NodeId = nodeId
                              NodeType = "Validate"
                              StartedAt = startTime
                              Status = NodeStatus.Failed(err, sw.ElapsedMilliseconds)
                              Input = Some content
                              Output = None
                              Confidence = None
                              TokensUsed = None }
                | None ->
                    sw.Stop()

                    let mockOutput =
                        sprintf "[Mock] Validation passed for %d invariants" invariants.Length

                    return
                        { NodeId = nodeId
                          NodeType = "Validate"
                          StartedAt = startTime
                          Status = NodeStatus.Completed(mockOutput, sw.ElapsedMilliseconds)
                          Input = Some content
                          Output = Some mockOutput
                          Confidence = Some 0.8
                          TokensUsed = None }
            }

        /// <summary>
        /// Execute a single node with full service integration.
        /// </summary>
        let executeNode
            (services: ControllerServices)
            (state: ControllerState)
            (node: WoTNode)
            : Async<ControllerState * WoTTraceStep> =
            async {
                // Get context from previous steps
                let context =
                    state.ExecutedSteps |> List.choose (fun s -> s.Output) |> List.truncate 5

                let! traceStep =
                    match node.Kind with
                    | Reason -> executeReasonNode services node state.Plan.Metadata.SourceGoal context
                    | Tool ->
                        // Extract tool name from node metadata or ID
                        let toolName = node.Id.Replace("tool_", "")
                        executeToolNode services node toolName Map.empty
                    | Validate ->
                        let content = context |> String.concat "\n"

                        let invariants =
                            match node.Payload with
                            | :? ValidatePayload as p -> p.Invariants
                            | _ -> []

                        executeValidation services node.Id content invariants
                    | Memory ->
                        let query = sprintf "DESCRIBE <%s>" node.Id
                        executeKnowledgeOp services (MemoryOp.Query query) node.Id
                    | Control ->
                        async {
                            return
                                { NodeId = node.Id
                                  NodeType = "Control"
                                  StartedAt = DateTime.UtcNow
                                  Status = NodeStatus.Completed("Control node executed", 0L)
                                  Input = None
                                  Output = Some "Control flow processed"
                                  Confidence = Some 1.0
                                  TokensUsed = None }
                        }

                // Update state with new step
                let newState =
                    { state with
                        ExecutedSteps = traceStep :: state.ExecutedSteps
                        LastActivity = DateTime.UtcNow }

                return (newState, traceStep)
            }

        /// <summary>
        /// Run one integrated step of the controller.
        /// </summary>
        let stepIntegrated
            (services: ControllerServices)
            (state: ControllerState)
            : Async<ControllerState * RouterDecision option> =
            async {
                match state.ActiveNode with
                | None -> return (state, Some(Finalize("", 1.0)))

                | Some nodeId ->
                    let nodeOpt = state.Plan.Nodes |> List.tryFind (fun n -> n.Id = nodeId)

                    match nodeOpt with
                    | None ->
                        let remaining = state.PendingNodes |> List.filter (fun id -> id <> nodeId)
                        let newActive = remaining |> List.tryHead

                        return
                            ({ state with
                                PendingNodes = remaining
                                ActiveNode = newActive
                                LastActivity = DateTime.UtcNow },
                             None)

                    | Some node ->
                        // Execute the node
                        let! (stateAfterExec, traceStep) = executeNode services state node

                        // Critique the result
                        let critique = Critic.critique node state.Plan.Metadata.SourceGoal state.Plan.Policy

                        // Create routing context
                        let context =
                            { CurrentNode = node
                              ExecutedNodes = stateAfterExec.ExecutedSteps
                              RemainingBudget = state.Budget
                              ConstraintScore = None
                              FailedAttempts =
                                stateAfterExec.ExecutedSteps
                                |> List.filter (fun s ->
                                    match s.Status with
                                    | NodeStatus.Failed _ -> true
                                    | _ -> false)
                                |> List.groupBy (fun s -> s.NodeId)
                                |> List.map (fun (id, steps) -> (id, steps.Length))
                                |> Map.ofList
                              Goal = state.Plan.Metadata.SourceGoal }

                        // Make routing decision
                        let decision = Router.decide context (Some critique)

                        // Handle escalation if needed
                        let! needsHuman =
                            async {
                                match decision with
                                | Escalate(escNodeId, reason, urgency) ->
                                    let! response =
                                        handleEscalation
                                            services
                                            escNodeId
                                            reason
                                            urgency
                                            (stateAfterExec.ExecutedSteps
                                             |> List.tryHead
                                             |> Option.bind (fun s -> s.Output)
                                             |> Option.defaultValue "")

                                    return not response.Approved
                                | _ -> return false
                            }

                        // Move to next node
                        let remaining = stateAfterExec.PendingNodes |> List.filter (fun id -> id <> nodeId)
                        let newActive = remaining |> List.tryHead

                        let newState =
                            { stateAfterExec with
                                PendingNodes = remaining
                                ActiveNode = newActive
                                Critiques = stateAfterExec.Critiques |> Map.add nodeId critique
                                Decisions = (DateTime.UtcNow, decision) :: stateAfterExec.Decisions
                                HumanInputRequired = needsHuman
                                EscalationsPending =
                                    match decision with
                                    | Escalate(id, reason, urgency) ->
                                        (id, reason, urgency) :: stateAfterExec.EscalationsPending
                                    | _ -> stateAfterExec.EscalationsPending
                                LastActivity = DateTime.UtcNow }

                        return (newState, Some decision)
            }

        /// <summary>
        /// Run the full integrated controller loop.
        /// </summary>
        let runIntegrated
            (services: ControllerServices)
            (state: ControllerState)
            (maxSteps: int)
            : Async<ControllerState * DistilledOutput> =
            async {
                let rec loop currentState stepCount =
                    async {
                        if stepCount >= maxSteps then
                            return currentState
                        elif currentState.HumanInputRequired then
                            return currentState
                        elif currentState.ActiveNode.IsNone then
                            return currentState
                        else
                            let! (newState, decision) = stepIntegrated services currentState

                            match decision with
                            | Some(Finalize _) -> return newState
                            | Some(Escalate _) when newState.HumanInputRequired -> return newState
                            | _ -> return! loop newState (stepCount + 1)
                    }

                let! finalState = loop state 0

                // Log insights to knowledge ledger if available
                match services.KnowledgeService with
                | Some kSvc ->
                    let insights = Distiller.extractInsights finalState.ExecutedSteps

                    for insight in insights do
                        do! kSvc.LogInsight(insight, "WoT Controller")
                | None -> ()

                let distilled =
                    Distiller.distill finalState.ExecutedSteps state.Plan.Metadata.SourceGoal Prose

                return (finalState, distilled)
            }

        /// <summary>
        /// Create a fully integrated controller and run it.
        /// </summary>
        let executeGoal
            (services: ControllerServices)
            (goal: string)
            (budget: Budget)
            (maxSteps: int)
            : Async<ControllerState * DistilledOutput> =
            async {
                let initialState = init goal budget
                return! runIntegrated services initialState maxSteps
            }
