module Tars.Interface.Cli.Commands.MacroDemo

open System
open Serilog
open Tars.Metascript
open Tars.Metascript.Domain
open Tars.Metascript.Config
open Tars.Llm
open Tars.Llm.Routing

let run (logger: ILogger) =
    task {
        logger.Information("Starting Evolutive Grammar (Macro) Demo...")

        // 1. Setup minimal content
        // Instantiate FileMacroRegistry explicitly
        let registry = new FileMacroRegistry("macros")
        let registryInterface = registry :> IMacroRegistry

        let demoMacroName = "demo_greeting"

        // 2. Define a Macro (Sub-workflow)
        let macroWf =
            { Name = demoMacroName
              Description = "A specific greeting macro"
              Version = "1.0"
              Inputs = []
              Steps =
                [ { Id = "step1"
                    Type = "agent"
                    Agent = Some "Greeter"
                    Tool = None
                    Instruction = Some "Generate a warm greeting for the user."
                    Params = None
                    Context = None
                    DependsOn = None
                    Outputs = Some [ "greeting" ]
                    Tools = None } ] }

        // 3. Register the macro
        logger.Information("Registering macro '{MacroName}'...", demoMacroName)
        do! registryInterface.Register macroWf

        // Verify it exists
        let! listed = registryInterface.List()
        logger.Information("Registry contains: {Macros}", listed |> List.map (fun w -> w.Name))

        // 4. Define Main Workflow that calls the macro
        let mainWf =
            { Name = "main_workflow"
              Description = "Invokes a macro"
              Version = "1.0"
              Inputs = []
              Steps =
                [ { Id = "call_macro"
                    Type = demoMacroName // This triggers the macro lookup
                    Agent = None
                    Tool = None
                    Instruction = None
                    Params = None
                    Context = None
                    DependsOn = None
                    Outputs = Some [ "result" ]
                    Tools = None }

                  { Id = "review"
                    Type = "agent"
                    Agent = Some "Reviewer"
                    Tool = None
                    Instruction = Some "Review the greeting generated by the macro."
                    Params = None
                    Context =
                      Some
                          [ { StepId = "call_macro"
                              OutputName = "result" } ] // Assuming macro output is under 'result'
                    DependsOn = None
                    Outputs = Some [ "review" ]
                    Tools = None } ] }

        // 5. Setup Engine Context
        // (Mocking LLM/Tools for speed, or using real implementation if simple)
        let tools = new Tars.Tools.ToolRegistry()

        // Register MacroTools for macro management
        let macroTools = Tars.Tools.MacroTools.getTools registryInterface

        for tool in macroTools do
            tools.Register(tool)

        // Create routing config from default to avoid missing field errors
        let routingCfg: RoutingConfig =
            { RoutingConfig.Default with
                OllamaBaseUri = Uri("http://localhost:11434/")
                VllmBaseUri = Uri("http://localhost:8000/")
                OpenAIBaseUri = Uri("https://api.openai.com/")
                GoogleGeminiBaseUri = Uri("https://generativelanguage.googleapis.com/")
                AnthropicBaseUri = Uri("https://api.anthropic.com/")
                DefaultOllamaModel = "qwen2.5-coder:1.5b"
                DefaultVllmModel = "facebook/opt-125m"
                DefaultOpenAIModel = "gpt-3.5-turbo"
                DefaultGoogleGeminiModel = "gemini-pro"
                DefaultAnthropicModel = "claude-2"
                DefaultEmbeddingModel = "nomic-embed-text" }

        let svcCfg = { LlmServiceConfig.Routing = routingCfg }

        // Mock LLM for demo purposes to avoid needing a running server
        let llmInterface =
            { new ILlmService with
                member _.CompleteAsync(req) =
                    task {
                        let lastMsg =
                            req.Messages
                            |> List.tryLast
                            |> Option.map (fun m -> m.Content)
                            |> Option.defaultValue ""

                        let responseText = $"Mock response for instruction: {lastMsg}"

                        return
                            { Text = responseText
                              Usage =
                                Some
                                    { PromptTokens = 10
                                      CompletionTokens = 10
                                      TotalTokens = 20 }
                              FinishReason = Some "stop"
                              Raw = None }
                    }

                member _.EmbedAsync(text) = task { return Array.zeroCreate 1536 } // Mock embedding
 
                member _.RouteAsync(req) = 
                    task { 
                        return { Backend = Ollama "mock"; Endpoint = Uri("http://localhost:11434"); ApiKey = None } 
                    }

                member _.CompleteStreamAsync(req, onToken) =
                    task { return raise (NotImplementedException("Stream not supported in mock")) } }

        let metaCtx =
            { MetascriptContext.Llm = llmInterface
              Tools = tools
              Budget = None
              VectorStore = None
              KnowledgeGraph = None
              SemanticMemory = None
              EpisodeService = None
              RagConfig = RagConfig.Default
              MacroRegistry = Some registryInterface
              MetascriptRegistry = None }

        // 6. Execute Main Workflow
        logger.Information("Executing main workflow...")

        try
            let! finalState = Engine.run metaCtx mainWf Map.empty

            logger.Information("Workflow completed.")

            // Check outputs
            match finalState.StepOutputs.TryFind "call_macro" with
            | Some outs -> logger.Information("Macro Output: {Output}", outs)
            | None -> logger.Error("Macro step produced no output!")

            match finalState.StepOutputs.TryFind "review" with
            | Some outs -> logger.Information("Review Output: {Output}", outs)
            | None -> logger.Error("Review step produced no output!")

        with ex ->
            logger.Error(ex, "Execution failed")

        return 0
    }
